// Localized copy for the companion customize modal. Kept in its own module so
// both the daily-quest plate panel and the daily-goal modal can import the
// strings without pulling in a component (and so Fast Refresh stays happy).
const CUSTOMIZE_MODAL_COPY = {
  en: {
    edit: "Customize companion",
    name: "Name",
    companion: "Companion",
    dog: "Dog",
    alien: "Alien",
    ghost: "Ghost",
    robot: "Robot",
    save: "Save",
    cancel: "Cancel",
  },
  es: {
    edit: "Personaliza tu compañero",
    name: "Nombre",
    companion: "Compañero",
    dog: "Perro",
    alien: "Alienígena",
    ghost: "Fantasma",
    robot: "Robot",
    save: "Guardar",
    cancel: "Cancelar",
  },
  pt: {
    edit: "Personalize seu companheiro",
    name: "Nome",
    companion: "Companheiro",
    dog: "Cachorro",
    alien: "Alienígena",
    ghost: "Fantasma",
    robot: "Robô",
    save: "Salvar",
    cancel: "Cancelar",
  },
  fr: {
    edit: "Personnalise ton compagnon",
    name: "Nom",
    companion: "Compagnon",
    dog: "Chien",
    alien: "Extraterrestre",
    ghost: "Fantôme",
    robot: "Robot",
    save: "Enregistrer",
    cancel: "Annuler",
  },
  it: {
    edit: "Personalizza il compagno",
    name: "Nome",
    companion: "Compagno",
    dog: "Cane",
    alien: "Alieno",
    ghost: "Fantasma",
    robot: "Robot",
    save: "Salva",
    cancel: "Annulla",
  },
  de: {
    edit: "Begleiter anpassen",
    name: "Name",
    companion: "Begleiter",
    dog: "Hund",
    alien: "Außerirdischer",
    ghost: "Gespenst",
    robot: "Roboter",
    save: "Speichern",
    cancel: "Abbrechen",
  },
  ja: {
    edit: "相棒をカスタマイズ",
    name: "名前",
    companion: "相棒",
    dog: "犬",
    alien: "宇宙人",
    ghost: "おばけ",
    robot: "ロボット",
    save: "保存",
    cancel: "キャンセル",
  },
  zh: {
    edit: "自定义伙伴",
    name: "名字",
    companion: "伙伴",
    dog: "狗狗",
    alien: "外星人",
    ghost: "幽灵",
    robot: "机器人",
    save: "保存",
    cancel: "取消",
  },
  hi: {
    edit: "साथी को कस्टमाइज़ करें",
    name: "नाम",
    companion: "साथी",
    dog: "कुत्ता",
    alien: "एलियन",
    ghost: "भूत",
    robot: "रोबोट",
    save: "सहेजें",
    cancel: "रद्द करें",
  },
  ar: {
    edit: "خصص صاحبك",
    name: "الاسم",
    companion: "الرفيق",
    dog: "كلب",
    alien: "كائن فضائي",
    ghost: "شبح",
    robot: "روبوت",
    save: "حفظ",
    cancel: "إلغاء",
  },
};

export function getCustomizeModalCopy(lang) {
  return CUSTOMIZE_MODAL_COPY[lang] || CUSTOMIZE_MODAL_COPY.en;
}
