// Localized copy for the companion customize modal. Kept in its own module so
// both the daily-quest plate panel and the daily-goal modal can import the
// strings without pulling in a component (and so Fast Refresh stays happy).
const CUSTOMIZE_MODAL_COPY = {
  en: {
    edit: "Customize companion",
    name: "Name",
    companion: "Companion",
    gameCompanion: "Game companion",
    girl: "Girl",
    rpgDescription: "This only changes your companion in the RPG game.",
    dog: "Dog",
    alien: "Alien",
    ghost: "Ghost",
    robot: "Robot",
    slime: "Slime",
    axolotl: "Axolotl",
    starter: "Starter",
    unlockLevel: "Level {level}",
    locked: "Locked",
    save: "Save",
    cancel: "Cancel",
  },
  es: {
    edit: "Personaliza tu compañero",
    name: "Nombre",
    companion: "Compañero",
    gameCompanion: "Compañero del juego",
    girl: "Chica",
    rpgDescription: "Esto solo cambia a tu compañero en el juego RPG.",
    dog: "Perro",
    alien: "Alienígena",
    ghost: "Fantasma",
    robot: "Robot",
    slime: "Slime",
    axolotl: "Ajolote",
    starter: "Inicial",
    unlockLevel: "Nivel {level}",
    locked: "Bloqueado",
    save: "Guardar",
    cancel: "Cancelar",
  },
  pt: {
    edit: "Personalize seu companheiro",
    name: "Nome",
    companion: "Companheiro",
    gameCompanion: "Companheiro do jogo",
    girl: "Garota",
    rpgDescription: "Isso só muda seu companheiro no jogo RPG.",
    dog: "Cachorro",
    alien: "Alienígena",
    ghost: "Fantasma",
    robot: "Robô",
    slime: "Slime",
    axolotl: "Axolote",
    starter: "Inicial",
    unlockLevel: "Nível {level}",
    locked: "Bloqueado",
    save: "Salvar",
    cancel: "Cancelar",
  },
  fr: {
    edit: "Personnalise ton compagnon",
    name: "Nom",
    companion: "Compagnon",
    gameCompanion: "Compagnon de jeu",
    girl: "Fille",
    rpgDescription: "Cela change uniquement ton compagnon dans le jeu RPG.",
    dog: "Chien",
    alien: "Extraterrestre",
    ghost: "Fantôme",
    robot: "Robot",
    slime: "Slime",
    axolotl: "Axolotl",
    starter: "Depart",
    unlockLevel: "Niveau {level}",
    locked: "Verrouille",
    save: "Enregistrer",
    cancel: "Annuler",
  },
  it: {
    edit: "Personalizza il compagno",
    name: "Nome",
    companion: "Compagno",
    gameCompanion: "Compagno di gioco",
    girl: "Ragazza",
    rpgDescription: "Questo cambia solo il tuo compagno nel gioco RPG.",
    dog: "Cane",
    alien: "Alieno",
    ghost: "Fantasma",
    robot: "Robot",
    slime: "Slime",
    axolotl: "Axolotl",
    starter: "Iniziale",
    unlockLevel: "Livello {level}",
    locked: "Bloccato",
    save: "Salva",
    cancel: "Annulla",
  },
  de: {
    edit: "Begleiter anpassen",
    name: "Name",
    companion: "Begleiter",
    gameCompanion: "Spielbegleiter",
    girl: "Mädchen",
    rpgDescription: "Dies ändert nur deinen Begleiter im RPG-Spiel.",
    dog: "Hund",
    alien: "Außerirdischer",
    ghost: "Gespenst",
    robot: "Roboter",
    slime: "Schleim",
    axolotl: "Axolotl",
    starter: "Start",
    unlockLevel: "Level {level}",
    locked: "Gesperrt",
    save: "Speichern",
    cancel: "Abbrechen",
  },
  ja: {
    edit: "相棒をカスタマイズ",
    name: "名前",
    companion: "相棒",
    gameCompanion: "ゲームの相棒",
    girl: "女の子",
    rpgDescription: "これはRPGゲーム内の相棒だけを変更します。",
    dog: "犬",
    alien: "宇宙人",
    ghost: "おばけ",
    robot: "ロボット",
    slime: "スライム",
    axolotl: "ウーパールーパー",
    starter: "スターター",
    unlockLevel: "レベル {level}",
    locked: "ロック中",
    save: "保存",
    cancel: "キャンセル",
  },
  zh: {
    edit: "自定义伙伴",
    name: "名字",
    companion: "伙伴",
    gameCompanion: "游戏伙伴",
    girl: "女孩",
    rpgDescription: "这只会更改 RPG 游戏中的伙伴。",
    dog: "狗狗",
    alien: "外星人",
    ghost: "幽灵",
    robot: "机器人",
    slime: "史莱姆",
    axolotl: "六角恐龙",
    starter: "初始",
    unlockLevel: "等级 {level}",
    locked: "已锁定",
    save: "保存",
    cancel: "取消",
  },
  hi: {
    edit: "साथी को कस्टमाइज़ करें",
    name: "नाम",
    companion: "साथी",
    gameCompanion: "गेम साथी",
    girl: "लड़की",
    rpgDescription: "यह केवल RPG गेम में आपके साथी को बदलता है।",
    dog: "कुत्ता",
    alien: "एलियन",
    ghost: "भूत",
    robot: "रोबोट",
    slime: "स्लाइम",
    axolotl: "एक्सोलॉटल",
    starter: "शुरुआती",
    unlockLevel: "स्तर {level}",
    locked: "लॉक",
    save: "सहेजें",
    cancel: "रद्द करें",
  },
  ar: {
    edit: "خصص صاحبك",
    name: "الاسم",
    companion: "الرفيق",
    gameCompanion: "رفيق اللعبة",
    girl: "الفتاة",
    rpgDescription: "هذا يغيّر رفيقك في لعبة تقمص الأدوار فقط.",
    dog: "كلب",
    alien: "كائن فضائي",
    ghost: "شبح",
    robot: "روبوت",
    slime: "سلايم",
    axolotl: "أكسولوتل",
    starter: "البداية",
    unlockLevel: "المستوى {level}",
    locked: "مقفول",
    save: "حفظ",
    cancel: "إلغاء",
  },
};

export function getCustomizeModalCopy(lang) {
  return CUSTOMIZE_MODAL_COPY[lang] || CUSTOMIZE_MODAL_COPY.en;
}
