export const LANGUAGE_POSTCARDS = {
  nl: {
    greeting: "Dank je wel!",
    greetingMeaning: "thankYou",
    phrase: "Hoe gaat het?",
    phraseMeaning: "howAreYou",
    native: "Nederlands",
    x: 15,
    y: 13,
    tilt: -9,
    tone: "peach",
  },
  en: {
    greeting: "Hello!",
    greetingMeaning: "hello",
    phrase: "How are you?",
    phraseMeaning: "howAreYou",
    native: "English",
    x: 65,
    y: 9,
    tilt: 7,
    tone: "mint",
  },
  fr: {
    greeting: "Ça va ?",
    greetingMeaning: "howAreYou",
    phrase: "Merci !",
    phraseMeaning: "thankYou",
    native: "Français",
    x: 10,
    y: 36,
    tilt: -7,
    tone: "lilac",
  },
  de: {
    greeting: "Guten Tag!",
    greetingMeaning: "goodDay",
    phrase: "Wie geht’s?",
    phraseMeaning: "howAreYou",
    native: "Deutsch",
    x: 84,
    y: 28,
    tilt: 9,
    tone: "peach",
  },
  it: {
    greeting: "Come stai?",
    greetingMeaning: "howAreYou",
    phrase: "Grazie!",
    phraseMeaning: "thankYou",
    native: "Italiano",
    x: 63,
    y: 48,
    tilt: -6,
    tone: "peach",
  },
  pt: {
    greeting: "Tudo bem?",
    greetingMeaning: "howAreYou",
    phrase: "Até logo!",
    phraseMeaning: "seeYou",
    native: "Português",
    x: 30,
    y: 61,
    tilt: 8,
    tone: "mint",
  },
  es: {
    greeting: "¡Hola!",
    greetingMeaning: "hello",
    phrase: "¿Cómo estás?",
    phraseMeaning: "howAreYou",
    native: "Español",
    x: 55,
    y: 82,
    tilt: -8,
    tone: "peach",
  },
  el: {
    greeting: "Καλημέρα!",
    greetingMeaning: "goodMorning",
    phrase: "Τι κάνεις;",
    phraseMeaning: "howAreYou",
    native: "Ελληνικά",
    x: 11,
    y: 76,
    tilt: -8,
    tone: "mint",
  },
  ga: {
    greeting: "Go raibh maith agat!",
    greetingMeaning: "thankYou",
    phrase: "Conas atá tú?",
    phraseMeaning: "howAreYou",
    native: "Gaeilge",
    x: 26,
    y: 93,
    tilt: 5,
    tone: "peach",
  },
  ja: {
    greeting: "ありがとう",
    greetingMeaning: "thankYou",
    phrase: "お元気ですか？",
    phraseMeaning: "howAreYou",
    native: "日本語",
    x: 41,
    y: 30,
    tilt: 5,
    tone: "lilac",
  },
  pl: {
    greeting: "Dzień dobry!",
    greetingMeaning: "goodDay",
    phrase: "Jak się masz?",
    phraseMeaning: "howAreYou",
    native: "Polski",
    x: 83,
    y: 61,
    tilt: 8,
    tone: "lilac",
  },
  ru: {
    greeting: "Как дела?",
    greetingMeaning: "howAreYou",
    phrase: "Спасибо!",
    phraseMeaning: "thankYou",
    native: "Русский",
    x: 84,
    y: 89,
    tilt: -5,
    tone: "mint",
  },
};

// Pick each language's opening once per visit from its phrase pool.
// Keep the phrase and its translation together.
export function createLanguagePostcards(random = Math.random) {
  return Object.fromEntries(Object.entries(LANGUAGE_POSTCARDS).map(([code, card]) => {
    if (code === "en" || code === "es" || random() < 0.5) return [code, { ...card }];
    return [code, { ...card,
      greeting: card.phrase, greetingMeaning: card.phraseMeaning,
      phrase: card.greeting, phraseMeaning: card.greetingMeaning,
    }];
  }));
}

export const languageAtlasCopy = {
  en: {
    meanings: {
      hello: "Hello!",
      goodMorning: "Good morning!",
      goodDay: "Good day!",
      niceToMeet: "Nice to meet you!",
      howAreYou: "How are you?",
      thankYou: "Thank you!",
      seeYou: "See you later!",
    },
    title: "Piyali means hello.",
    intro: "Practice in 12 languages. Connect with new cultures, create opportunity or improve your confidence in speaking your native tongue.",
  },
  es: {
    meanings: {
      hello: "¡Hola!",
      goodMorning: "¡Buenos días!",
      goodDay: "¡Buen día!",
      niceToMeet: "¡Mucho gusto!",
      howAreYou: "¿Cómo estás?",
      thankYou: "¡Gracias!",
      seeYou: "¡Hasta luego!",
    },
    title: "Piyali significa hola.",
    intro: "Practica en 12 idiomas. Conecta con nuevas culturas, crea oportunidades o mejora tu confianza al hablar tu lengua materna.",
  },
  pt: {
    meanings: {
      hello: "Olá!",
      goodMorning: "Bom dia!",
      goodDay: "Bom dia!",
      niceToMeet: "Prazer em conhecer você!",
      howAreYou: "Como você está?",
      thankYou: "Obrigado!",
      seeYou: "Até logo!",
    },
    title: "Piyali significa olá.",
    intro: "Pratique em 12 idiomas. Conecte-se com novas culturas, crie oportunidades ou ganhe confiança ao falar sua língua materna.",
  },
  fr: {
    meanings: {
      hello: "Bonjour !",
      goodMorning: "Bonjour !",
      goodDay: "Bonjour !",
      niceToMeet: "Enchanté !",
      howAreYou: "Comment ça va ?",
      thankYou: "Merci !",
      seeYou: "À bientôt !",
    },
    title: "Piyali signifie bonjour.",
    intro: "Pratiquez 12 langues. Découvrez de nouvelles cultures, créez des opportunités ou gagnez en confiance dans votre langue maternelle.",
  },
  it: {
    meanings: {
      hello: "Ciao!",
      goodMorning: "Buongiorno!",
      goodDay: "Buongiorno!",
      niceToMeet: "Piacere di conoscerti!",
      howAreYou: "Come stai?",
      thankYou: "Grazie!",
      seeYou: "A presto!",
    },
    title: "Piyali significa ciao.",
    intro: "Esercitati in 12 lingue. Entra in contatto con nuove culture, crea opportunità o acquista fiducia nel parlare la tua lingua madre.",
  },
  de: {
    meanings: {
      hello: "Hallo!",
      goodMorning: "Guten Morgen!",
      goodDay: "Guten Tag!",
      niceToMeet: "Schön, dich kennenzulernen!",
      howAreYou: "Wie geht’s dir?",
      thankYou: "Danke!",
      seeYou: "Bis später!",
    },
    title: "Piyali bedeutet Hallo.",
    intro: "Übe in 12 Sprachen. Entdecke neue Kulturen, schaffe Chancen oder gewinne Sicherheit beim Sprechen deiner Muttersprache.",
  },
  ja: {
    meanings: {
      hello: "こんにちは！",
      goodMorning: "おはよう！",
      goodDay: "こんにちは！",
      niceToMeet: "はじめまして！",
      howAreYou: "元気ですか？",
      thankYou: "ありがとう！",
      seeYou: "またね！",
    },
    title: "Piyaliは「こんにちは」という意味です。",
    intro: "12の言語で練習できます。新しい文化とつながり、機会を広げ、母語を話す自信も高めましょう。",
  },
  zh: {
    meanings: {
      hello: "你好！",
      goodMorning: "早上好！",
      goodDay: "你好！",
      niceToMeet: "很高兴认识你！",
      howAreYou: "你好吗？",
      thankYou: "谢谢！",
      seeYou: "回头见！",
    },
    title: "Piyali意为“你好”。",
    intro: "练习12种语言。连接新文化，创造机会，或增强说母语的信心。",
  },
  hi: {
    meanings: {
      hello: "नमस्ते!",
      goodMorning: "सुप्रभात!",
      goodDay: "नमस्ते!",
      niceToMeet: "आपसे मिलकर खुशी हुई!",
      howAreYou: "आप कैसे हैं?",
      thankYou: "धन्यवाद!",
      seeYou: "फिर मिलेंगे!",
    },
    title: "Piyali का मतलब नमस्ते है।",
    intro: "12 भाषाओं में अभ्यास करें। नई संस्कृतियों से जुड़ें, अवसर बनाएँ या अपनी मातृभाषा बोलने का आत्मविश्वास बढ़ाएँ।",
  },
  ar: {
    meanings: {
      hello: "أهلًا!",
      goodMorning: "صباح الخير!",
      goodDay: "نهارك سعيد!",
      niceToMeet: "تشرفت بمعرفتك!",
      howAreYou: "إزيك؟",
      thankYou: "شكرًا!",
      seeYou: "أشوفك بعدين!",
    },
    title: "Piyali معناها أهلًا.",
    intro: "اتمرن بـ12 لغة. اتعرف على ثقافات جديدة، افتح فرص، أو زوّد ثقتك في الكلام بلغتك الأم.",
  },
};
