// The landing page supports the same UI languages as the account flow.
export const landingPageRefreshCopy = {
  en: {
    heroSubtitle: "Practice speaking without the pressure. Piyali remembers your goals, helps you learn from mistakes, and plans what to practice next.",
    costQuestion: "How much does it cost?",
    costAnswer: "You can start for free and unlock the app for as little as $4 a month. A subscription also provides additional access to a coding education platform and subscriber content on finance, business, and software engineering, while supporting the creation of scholarships.",
    previousCompanion: "Previous companion",
    nextCompanion: "Next companion",
    title: "A truly personalized tutor",
    intro: "Making mistakes in front of a tutor can feel embarrassing. Practice privately with Piyali and try again as often as you need. Your tutor remembers what you find difficult and adapts to your goals and progress.",
    speak: "Speak",
    remember: "Remember",
    grow: "Grow",
    before: "Your first try",
    after: "A little better",
    memoryGoalLabel: "Your goal",
    memoryGoal: "Talking to my wife's grandma",
    memoryTomorrow: "For tomorrow",
    memoryLesson: "Lesson",
    memoryTutorSession: "Tutor session",
    memoryFlashcards: "Flashcards",
    browse: "Explore all the tools",
    close: "Close the toolkit",
    journey: "Learn a language with confidence",
    journeyNote: "As enjoyable as Duolingo, but calmer and more effective for learning",
    practiceModesBenefit: "{modes} practice modes to fit your needs, whether you need to learn quickly for a trip or learn deeply to connect with a new culture.",
    signupIntro: "All we need is a user name and you'll be ready to start!",
  },
  es: {
    heroSubtitle: "Practica hablar sin presión. Piyali recuerda tus metas, te ayuda a aprender de los errores y organiza lo que practicarás después.",
    costQuestion: "¿Cuánto cuesta?",
    costAnswer: "Puedes empezar gratis y desbloquear la app desde $4 USD al mes. La suscripción también ofrece acceso adicional a una plataforma educativa de programación y contenido para suscriptores sobre finanzas, negocios e ingeniería de software, además de apoyar la creación de becas.",
    previousCompanion: "Compañero anterior",
    nextCompanion: "Siguiente compañero",
    title: "Un tutor realmente personalizado",
    intro: "Equivocarte frente a un tutor puede dar vergüenza. Practica en privado con Piyali y vuelve a intentarlo las veces que necesites. Tu tutor recuerda lo que te cuesta y se adapta a tus metas y progreso.",
    speak: "Habla",
    remember: "Recuerda",
    grow: "Crece",
    before: "Tu primer intento",
    after: "Un poco mejor",
    memoryGoalLabel: "Tu meta",
    memoryGoal: "Hablar con la abuela de mi esposa",
    memoryTomorrow: "Para mañana",
    memoryLesson: "Lección",
    memoryTutorSession: "Sesión de tutor",
    memoryFlashcards: "Tarjetas",
    browse: "Explora todas las herramientas",
    close: "Cerrar las herramientas",
    journey: "Aprende un idioma con confianza",
    journeyNote: "Tan divertido como Duolingo, pero más tranquilo y más eficaz para aprender",
    practiceModesBenefit: "{modes} modos de práctica para tus necesidades, ya sea aprender rápido para un viaje o profundizar para conectar con una nueva cultura.",
    signupIntro: "¡Solo necesitamos un nombre de usuario y estarás listo para empezar!",
  },
  pt: {
    heroSubtitle: "Pratique a fala sem pressão. Piyali lembra suas metas, ajuda você a aprender com os erros e planeja o que praticar a seguir.",
    costQuestion: "Quanto custa?",
    costAnswer: "Você pode começar de graça e desbloquear o app a partir de US$ 4 por mês. A assinatura também oferece acesso adicional a uma plataforma de ensino de programação e conteúdo para assinantes sobre finanças, negócios e engenharia de software, além de apoiar a criação de bolsas de estudo.",
    previousCompanion: "Companheiro anterior",
    nextCompanion: "Próximo companheiro",
    title: "Um tutor realmente personalizado",
    intro: "Errar na frente de um tutor pode dar vergonha. Pratique em particular com Piyali e tente de novo quantas vezes precisar. Seu tutor lembra suas dificuldades e se adapta às suas metas e progresso.",
    speak: "Fale",
    remember: "Lembre",
    grow: "Cresça",
    before: "Sua primeira tentativa",
    after: "Um pouco melhor",
    memoryGoalLabel: "Sua meta",
    memoryGoal: "Conversar com a avó da minha esposa",
    memoryTomorrow: "Para amanhã",
    memoryLesson: "Lição",
    memoryTutorSession: "Sessão com tutor",
    memoryFlashcards: "Flashcards",
    browse: "Explore todas as ferramentas",
    close: "Fechar as ferramentas",
    journey: "Aprenda um idioma com confiança",
    journeyNote: "Tão divertido quanto Duolingo, mas mais tranquilo e mais eficaz para aprender",
    practiceModesBenefit: "{modes} modos de prática para suas necessidades, seja para aprender rápido para uma viagem ou aprofundar o aprendizado para se conectar com uma nova cultura.",
    signupIntro: "Só precisamos de um nome de usuário e você estará pronto para começar!",
  },
  fr: {
    heroSubtitle: "Pratiquez l’oral sans pression. Piyali retient vos objectifs, vous aide à apprendre de vos erreurs et prépare vos prochaines séances.",
    costQuestion: "Combien ça coûte ?",
    costAnswer: "Vous pouvez commencer gratuitement et débloquer l’application à partir de 4 $ US par mois. L’abonnement offre aussi un accès supplémentaire à une plateforme d’apprentissage de la programmation et à du contenu réservé aux abonnés sur la finance, les affaires et l’ingénierie logicielle, tout en soutenant la création de bourses.",
    previousCompanion: "Compagnon précédent",
    nextCompanion: "Compagnon suivant",
    title: "Un tuteur vraiment personnalisé",
    intro: "Faire des erreurs devant un tuteur peut être gênant. Pratiquez en privé avec Piyali et réessayez autant que nécessaire. Votre tuteur retient vos difficultés et s’adapte à vos objectifs et à vos progrès.",
    speak: "Parler",
    remember: "Retenir",
    grow: "Progresser",
    before: "Votre premier essai",
    after: "Un peu mieux",
    memoryGoalLabel: "Votre objectif",
    memoryGoal: "Parler avec la grand-mère de ma femme",
    memoryTomorrow: "Pour demain",
    memoryLesson: "Leçon",
    memoryTutorSession: "Séance avec le tuteur",
    memoryFlashcards: "Cartes mémoire",
    browse: "Explorer tous les outils",
    close: "Fermer les outils",
    journey: "Apprenez une langue avec confiance",
    journeyNote: "Aussi agréable que Duolingo, mais plus calme et plus efficace pour apprendre",
    practiceModesBenefit: "{modes} modes de pratique selon vos besoins : apprendre rapidement pour un voyage ou approfondir vos connaissances pour découvrir une nouvelle culture.",
    signupIntro: "Il nous suffit d’un nom d’utilisateur et vous pourrez commencer !",
  },
  it: {
    heroSubtitle: "Esercitati a parlare senza pressione. Piyali ricorda i tuoi obiettivi, ti aiuta a imparare dagli errori e pianifica cosa praticare dopo.",
    costQuestion: "Quanto costa?",
    costAnswer: "Puoi iniziare gratis e sbloccare l’app a partire da 4 USD al mese. L’abbonamento offre anche accesso aggiuntivo a una piattaforma educativa di programmazione e contenuti per gli abbonati su finanza, business e ingegneria del software, contribuendo alla creazione di borse di studio.",
    previousCompanion: "Compagno precedente",
    nextCompanion: "Compagno successivo",
    title: "Un tutor davvero personalizzato",
    intro: "Sbagliare davanti a un tutor può essere imbarazzante. Esercitati in privato con Piyali e riprova tutte le volte che ti servono. Il tutor ricorda le tue difficoltà e si adatta ai tuoi obiettivi e progressi.",
    speak: "Parla",
    remember: "Ricorda",
    grow: "Cresci",
    before: "Il tuo primo tentativo",
    after: "Un po’ meglio",
    memoryGoalLabel: "Il tuo obiettivo",
    memoryGoal: "Parlare con la nonna di mia moglie",
    memoryTomorrow: "Per domani",
    memoryLesson: "Lezione",
    memoryTutorSession: "Sessione con il tutor",
    memoryFlashcards: "Flashcard",
    browse: "Esplora tutti gli strumenti",
    close: "Chiudi gli strumenti",
    journey: "Impara una lingua con fiducia",
    journeyNote: "Piacevole come Duolingo, ma più tranquillo e più efficace per imparare",
    practiceModesBenefit: "{modes} modalità di pratica per le tue esigenze, per imparare rapidamente in vista di un viaggio o approfondire per entrare in contatto con una nuova cultura.",
    signupIntro: "Ci basta un nome utente e sarai pronto per iniziare!",
  },
  de: {
    heroSubtitle: "Übe das Sprechen ohne Druck. Piyali merkt sich deine Ziele, hilft dir, aus Fehlern zu lernen, und plant, was du als Nächstes übst.",
    costQuestion: "Wie viel kostet es?",
    costAnswer: "Du kannst kostenlos starten und die App ab 4 US-Dollar im Monat freischalten. Ein Abo bietet außerdem zusätzlichen Zugang zu einer Lernplattform für Programmierung und Inhalten für Abonnenten zu Finanzen, Wirtschaft und Softwareentwicklung und unterstützt die Vergabe von Stipendien.",
    previousCompanion: "Vorheriger Begleiter",
    nextCompanion: "Nächster Begleiter",
    title: "Ein Tutor, der sich auf dich einstellt",
    intro: "Fehler vor einem Tutor können sich peinlich anfühlen. Übe mit Piyali in privatem Rahmen und versuche es so oft, wie du möchtest. Dein Tutor merkt sich deine Schwierigkeiten und passt sich deinen Zielen und Fortschritten an.",
    speak: "Sprechen",
    remember: "Merken",
    grow: "Wachsen",
    before: "Dein erster Versuch",
    after: "Ein bisschen besser",
    memoryGoalLabel: "Dein Ziel",
    memoryGoal: "Mit der Oma meiner Frau sprechen",
    memoryTomorrow: "Für morgen",
    memoryLesson: "Lektion",
    memoryTutorSession: "Tutor-Sitzung",
    memoryFlashcards: "Karteikarten",
    browse: "Alle Werkzeuge entdecken",
    close: "Werkzeuge schließen",
    journey: "Lerne eine Sprache mit Selbstvertrauen",
    journeyNote: "So unterhaltsam wie Duolingo, aber ruhiger und effektiver beim Lernen",
    practiceModesBenefit: "{modes} Übungsmodi für deine Bedürfnisse: schnell für eine Reise lernen oder tiefer einsteigen, um eine neue Kultur kennenzulernen.",
    signupIntro: "Wir brauchen nur einen Benutzernamen, dann kannst du loslegen!",
  },
  ja: {
    heroSubtitle: "プレッシャーを感じずに会話を練習しましょう。Piyaliはあなたの目標を覚え、間違いから学ぶのを助け、次の練習を計画します。",
    costQuestion: "料金はいくらですか？",
    costAnswer: "無料で始められ、月額4米ドルからアプリの機能を利用できます。サブスクリプションには、プログラミング教育プラットフォームへの追加アクセスと、金融・ビジネス・ソフトウェアエンジニアリングに関する会員向けコンテンツも含まれ、奨学金の創設を支援します。",
    previousCompanion: "前の仲間",
    nextCompanion: "次の仲間",
    title: "あなたに合わせたチューター",
    intro: "チューターの前で間違えるのは恥ずかしく感じることがあります。Piyaliと個別に練習し、必要なだけやり直せます。苦手なことを覚えて、目標と進歩に合わせて学習を調整します。",
    speak: "話す",
    remember: "覚える",
    grow: "成長する",
    before: "最初の挑戦",
    after: "少し上達",
    memoryGoalLabel: "あなたの目標",
    memoryGoal: "妻の祖母と話す",
    memoryTomorrow: "明日の練習",
    memoryLesson: "レッスン",
    memoryTutorSession: "チューターとの練習",
    memoryFlashcards: "フラッシュカード",
    browse: "すべてのツールを見る",
    close: "ツールを閉じる",
    journey: "自信を持って言語を学ぼう",
    journeyNote: "Duolingoのように楽しく、より落ち着いて効果的に学べます",
    practiceModesBenefit: "旅行に向けて短期間で学びたいときも、新しい文化を深く理解したいときも、目的に合わせて選べる{modes}つの練習モード。",
    signupIntro: "ユーザー名だけで、すぐに始められます！",
  },
  zh: {
    heroSubtitle: "轻松练习口语，不必有压力。Piyali会记住你的目标，帮助你从错误中学习，并安排接下来要练习的内容。",
    costQuestion: "费用是多少？",
    costAnswer: "你可以免费开始，每月低至4美元即可解锁应用。订阅还提供编程教育平台的额外访问权限，以及金融、商业和软件工程方面的订阅者专属内容，同时支持设立奖学金。",
    previousCompanion: "上一个伙伴",
    nextCompanion: "下一个伙伴",
    title: "真正为你量身定制的导师",
    intro: "在导师面前犯错可能让人尴尬。和Piyali私下练习，按需要反复尝试。你的导师会记住你的难点，并根据目标和进步调整练习。",
    speak: "开口说",
    remember: "记下来",
    grow: "持续成长",
    before: "第一次尝试",
    after: "更进一步",
    memoryGoalLabel: "你的目标",
    memoryGoal: "和我妻子的奶奶聊天",
    memoryTomorrow: "明天的练习",
    memoryLesson: "课程",
    memoryTutorSession: "导师会话",
    memoryFlashcards: "闪卡",
    browse: "探索所有工具",
    close: "收起工具",
    journey: "自信地学习一门语言",
    journeyNote: "像Duolingo一样有趣，但更平静，学习更有效",
    practiceModesBenefit: "{modes}种练习模式满足你的需要，无论是为旅行快速学习，还是深入学习以了解新的文化。",
    signupIntro: "只需一个用户名，你就可以开始了！",
  },
  hi: {
    heroSubtitle: "बिना दबाव के बोलने का अभ्यास करें। Piyali आपके लक्ष्य याद रखता है, गलतियों से सीखने में मदद करता है और अगले अभ्यास की योजना बनाता है।",
    costQuestion: "इसकी कीमत कितनी है?",
    costAnswer: "आप मुफ़्त में शुरू कर सकते हैं और केवल 4 अमेरिकी डॉलर प्रति माह से ऐप अनलॉक कर सकते हैं। सदस्यता से कोडिंग शिक्षा प्लेटफ़ॉर्म और वित्त, व्यवसाय व सॉफ़्टवेयर इंजीनियरिंग से जुड़ी सदस्य सामग्री तक अतिरिक्त पहुँच मिलती है, साथ ही छात्रवृत्तियाँ बनाने में मदद होती है।",
    previousCompanion: "पिछला साथी",
    nextCompanion: "अगला साथी",
    title: "आपके अनुसार ढला हुआ ट्यूटर",
    intro: "ट्यूटर के सामने गलती करना शर्मिंदगी महसूस करा सकता है। Piyali के साथ निजी तौर पर अभ्यास करें और जितनी बार ज़रूरत हो फिर कोशिश करें। आपका ट्यूटर आपकी कठिनाइयों को याद रखता है और लक्ष्यों व प्रगति के अनुसार ढलता है।",
    speak: "बोलें",
    remember: "याद रखें",
    grow: "आगे बढ़ें",
    before: "आपका पहला प्रयास",
    after: "थोड़ा बेहतर",
    memoryGoalLabel: "आपका लक्ष्य",
    memoryGoal: "अपनी पत्नी की दादी से बात करना",
    memoryTomorrow: "कल के लिए",
    memoryLesson: "पाठ",
    memoryTutorSession: "ट्यूटर सत्र",
    memoryFlashcards: "फ़्लैशकार्ड",
    browse: "सभी टूल देखें",
    close: "टूल बंद करें",
    journey: "आत्मविश्वास के साथ भाषा सीखें",
    journeyNote: "Duolingo जितना मज़ेदार, लेकिन सीखने के लिए अधिक शांत और प्रभावी",
    practiceModesBenefit: "आपकी ज़रूरतों के लिए {modes} अभ्यास मोड, चाहे यात्रा के लिए जल्दी सीखना हो या नई संस्कृति से जुड़ने के लिए गहराई से सीखना हो।",
    signupIntro: "हमें बस एक यूज़रनेम चाहिए और आप शुरू करने के लिए तैयार हैं!",
  },
  ar: {
    heroSubtitle: "اتمرن على الكلام من غير ضغط. Piyali بيفتكر أهدافك، بيساعدك تتعلم من أخطائك، وبيخطط لإيه تتمرن عليه بعد كده.",
    costQuestion: "التكلفة كام؟",
    costAnswer: "تقدر تبدأ مجانًا وتفتح إمكانيات التطبيق باشتراك يبدأ من 4 دولارات أمريكية في الشهر. الاشتراك بيوفر كمان وصول إضافي لمنصة لتعليم البرمجة ومحتوى للمشتركين عن التمويل والأعمال وهندسة البرمجيات، وبيساهم في إنشاء منح دراسية.",
    previousCompanion: "الرفيق السابق",
    nextCompanion: "الرفيق التالي",
    title: "مدرس متكيف معاك فعلًا",
    intro: "الغلط قدام مدرس ممكن يحرجك. اتمرن على انفراد مع Piyali وجرب تاني قد ما تحتاج. مدرسك بيفتكر اللي بيصعب عليك وبيتكيف مع أهدافك وتقدمك.",
    speak: "اتكلم",
    remember: "افتكر",
    grow: "اتطور",
    before: "محاولتك الأولى",
    after: "أحسن شوية",
    memoryGoalLabel: "هدفك",
    memoryGoal: "أتكلم مع جدة مراتي",
    memoryTomorrow: "لبكرة",
    memoryLesson: "درس",
    memoryTutorSession: "جلسة مع المدرس",
    memoryFlashcards: "بطاقات",
    browse: "اكتشف كل الأدوات",
    close: "اقفل الأدوات",
    journey: "اتعلم لغة بثقة",
    journeyNote: "ممتع زي Duolingo، لكن أهدى وأكثر فعالية في التعلم",
    practiceModesBenefit: "{modes} طرق للتدريب تناسب احتياجاتك، سواء عايز تتعلم بسرعة عشان رحلة أو تتعمق عشان تتواصل مع ثقافة جديدة.",
    signupIntro: "كل اللي محتاجينه اسم مستخدم وهتكون جاهز تبدأ!",
  },
};

// Section names were authored in uppercase for the former numbered labels.
export function landingSectionLabel(label, locale) {
  if (label !== label.toLocaleUpperCase(locale)) return label;
  return label.slice(0, 1) + label.slice(1).toLocaleLowerCase(locale);
}
