export const landingTutorDemoCopy = {
  en: {
    start: "Try it!",
    retry: "Try another short lesson",
    stop: "End lesson",
    cancel: "Cancel",
    connecting: "Connecting…",
    thinking: "One moment…",
    speaking: "Piyali is speaking",
    listening: "Your turn—say it out loud.",
    ended: "Nice practice! Ready for more?",
    language: "Select a language to practice",
    emptyTutor: "Piyali will start the conversation.",
    emptyLearner: "Your words will appear here.",
    microphoneDenied: "Allow microphone access to try the lesson.",
    microphoneUnavailable: "We couldn’t access a microphone. Check your device and try again.",
    unavailable: "Live practice is unavailable right now. Please try again later.",
  },
  es: {
    start: "¡Pruébalo!",
    retry: "Prueba otra lección corta",
    stop: "Terminar lección",
    cancel: "Cancelar",
    connecting: "Conectando…",
    thinking: "Un momento…",
    speaking: "Piyali está hablando",
    listening: "Tu turno: dilo en voz alta.",
    ended: "¡Buena práctica! ¿Quieres más?",
    language: "Selecciona un idioma para practicar",
    emptyTutor: "Piyali iniciará la conversación.",
    emptyLearner: "Tus palabras aparecerán aquí.",
    microphoneDenied: "Permite el acceso al micrófono para probar la lección.",
    microphoneUnavailable: "No pudimos acceder al micrófono. Revisa tu dispositivo e inténtalo de nuevo.",
    unavailable: "La práctica en vivo no está disponible ahora. Inténtalo más tarde.",
  },
  pt: {
    start: "Experimente!",
    retry: "Experimente outra aula curta",
    stop: "Encerrar aula",
    cancel: "Cancelar",
    connecting: "Conectando…",
    thinking: "Um momento…",
    speaking: "Piyali está falando",
    listening: "Sua vez: fale em voz alta.",
    ended: "Boa prática! Quer continuar?",
    language: "Selecione um idioma para praticar",
    emptyTutor: "Piyali vai iniciar a conversa.",
    emptyLearner: "Suas palavras aparecerão aqui.",
    microphoneDenied: "Permita o acesso ao microfone para experimentar a aula.",
    microphoneUnavailable: "Não foi possível acessar o microfone. Verifique seu dispositivo e tente novamente.",
    unavailable: "A prática ao vivo não está disponível agora. Tente mais tarde.",
  },
  fr: {
    start: "Essayez !",
    retry: "Essayez une autre courte leçon",
    stop: "Terminer la leçon",
    cancel: "Annuler",
    connecting: "Connexion…",
    thinking: "Un instant…",
    speaking: "Piyali parle",
    listening: "À vous : dites-le à voix haute.",
    ended: "Belle séance ! Envie de continuer ?",
    language: "Choisissez une langue à pratiquer",
    emptyTutor: "Piyali va lancer la conversation.",
    emptyLearner: "Vos paroles apparaîtront ici.",
    microphoneDenied: "Autorisez le micro pour essayer la leçon.",
    microphoneUnavailable: "Impossible d’accéder au micro. Vérifiez votre appareil et réessayez.",
    unavailable: "La pratique en direct est indisponible. Réessayez plus tard.",
  },
  it: {
    start: "Prova!",
    retry: "Prova un’altra lezione breve",
    stop: "Termina lezione",
    cancel: "Annulla",
    connecting: "Connessione…",
    thinking: "Un momento…",
    speaking: "Piyali sta parlando",
    listening: "Tocca a te: dillo ad alta voce.",
    ended: "Ottima pratica! Vuoi continuare?",
    language: "Scegli una lingua da praticare",
    emptyTutor: "Piyali inizierà la conversazione.",
    emptyLearner: "Le tue parole appariranno qui.",
    microphoneDenied: "Consenti l’accesso al microfono per provare la lezione.",
    microphoneUnavailable: "Impossibile accedere al microfono. Controlla il dispositivo e riprova.",
    unavailable: "La pratica dal vivo non è disponibile. Riprova più tardi.",
  },
  de: {
    start: "Probier’s aus!",
    retry: "Teste eine weitere kurze Lektion",
    stop: "Lektion beenden",
    cancel: "Abbrechen",
    connecting: "Verbindung wird aufgebaut…",
    thinking: "Einen Moment…",
    speaking: "Piyali spricht",
    listening: "Du bist dran: Sprich laut.",
    ended: "Gut geübt! Bereit für mehr?",
    language: "Wähle eine Sprache zum Üben",
    emptyTutor: "Piyali beginnt das Gespräch.",
    emptyLearner: "Deine Worte erscheinen hier.",
    microphoneDenied: "Erlaube den Mikrofonzugriff, um die Lektion auszuprobieren.",
    microphoneUnavailable: "Kein Mikrofonzugriff möglich. Prüfe dein Gerät und versuche es erneut.",
    unavailable: "Live-Übungen sind gerade nicht verfügbar. Versuche es später erneut.",
  },
  ja: {
    start: "試してみる！",
    retry: "もう一度短いレッスンを試す",
    stop: "レッスンを終了",
    cancel: "キャンセル",
    connecting: "接続中…",
    thinking: "少々お待ちください…",
    speaking: "Piyaliが話しています",
    listening: "あなたの番です。声に出してみましょう。",
    ended: "よくできました！続けてみますか？",
    language: "練習する言語を選んでください",
    emptyTutor: "Piyaliが会話を始めます。",
    emptyLearner: "あなたの言葉がここに表示されます。",
    microphoneDenied: "レッスンを試すにはマイクの使用を許可してください。",
    microphoneUnavailable: "マイクにアクセスできませんでした。端末を確認して再度お試しください。",
    unavailable: "ライブ練習は現在利用できません。後でもう一度お試しください。",
  },
  zh: {
    start: "试试看！",
    retry: "再试一节短课",
    stop: "结束课程",
    cancel: "取消",
    connecting: "连接中…",
    thinking: "请稍等…",
    speaking: "Piyali正在说话",
    listening: "轮到你了，大声说出来。",
    ended: "练得不错！想继续吗？",
    language: "选择要练习的语言",
    emptyTutor: "Piyali将开始对话。",
    emptyLearner: "你说的话会显示在这里。",
    microphoneDenied: "请允许使用麦克风以体验课程。",
    microphoneUnavailable: "无法使用麦克风。请检查设备后重试。",
    unavailable: "实时练习暂不可用。请稍后再试。",
  },
  hi: {
    start: "आज़माएँ!",
    retry: "एक और छोटा पाठ आज़माएँ",
    stop: "पाठ समाप्त करें",
    cancel: "रद्द करें",
    connecting: "जुड़ रहा है…",
    thinking: "एक क्षण…",
    speaking: "Piyali बोल रहा है",
    listening: "आपकी बारी: ज़ोर से बोलें।",
    ended: "अच्छा अभ्यास! आगे बढ़ना चाहते हैं?",
    language: "अभ्यास के लिए भाषा चुनें",
    emptyTutor: "Piyali बातचीत शुरू करेगा।",
    emptyLearner: "आपके शब्द यहाँ दिखाई देंगे।",
    microphoneDenied: "पाठ आज़माने के लिए माइक्रोफ़ोन की अनुमति दें।",
    microphoneUnavailable: "माइक्रोफ़ोन नहीं मिल सका। अपना डिवाइस जाँचें और फिर कोशिश करें।",
    unavailable: "लाइव अभ्यास अभी उपलब्ध नहीं है। बाद में फिर कोशिश करें।",
  },
  ar: {
    start: "جربه!",
    retry: "جرب درس قصير تاني",
    stop: "إنهاء الدرس",
    cancel: "إلغاء",
    connecting: "جاري الاتصال…",
    thinking: "لحظة…",
    speaking: "Piyali بيتكلم",
    listening: "دورك: قولها بصوت عالي.",
    ended: "تدريب حلو! جاهز تكمل؟",
    language: "اختار لغة للتدريب",
    emptyTutor: "Piyali هيبدأ المحادثة.",
    emptyLearner: "كلامك هيظهر هنا.",
    microphoneDenied: "اسمح باستخدام الميكروفون عشان تجرب الدرس.",
    microphoneUnavailable: "مش قادرين نوصل للميكروفون. راجع جهازك وجرب تاني.",
    unavailable: "التدريب المباشر مش متاح دلوقتي. جرب بعدين.",
  },
};
