// Copy for the six core landing-page capabilities.
export const landingCapabilityCopy = {
  "en": {
    "memoryTitle": "Today's Focus",
    "memoryDesc": "Today's focus is a memory system that takes into account your mistakes, goals, and recent progress to shape your daily practice, so you spend time on what needs attention.",
    "memoryDetail": "Set a goal, like talking to your wife’s grandma. Today’s Focus organizes tomorrow’s practice into lessons, tutor sessions, and flashcards.",
    "proficiencyTitle": "Proficiency",
    "proficiencyDesc": "From your first words to advanced conversation, follow a complete CEFR course with practice that adapts to your ability.",
    "proficiencyDetail": "CEFR guides your course. Score tracks overall ability from 0-100. Each graded answer, its difficulty, and the help you need refine your next challenge.",
    "companionDesc": "Build a steady practice habit with a companion that grows as you show up. Daily goals keep it healthy and give you a reason to return.",
    "connectedTitle": "Cross-platform Learning",
    "connectedDesc": "Cross-platform learning with Robots Building Education, a coding platform, lets you own your transcript and achievements, create teams across apps, and create scholarships through learning.",
    "immersionDesc": "Take your language beyond the app with daily, real-world tasks matched to your current abilities.",
    "modules": "Modules",
    "lessonReviews": "Lessons & reviews",
    "modes": "Practice modes",
    "vocabularyCards": "Vocabulary cards",
    "modeNames": [
      "Vocabulary",
      "Grammar",
      "Reading",
      "Stories",
      "Conversation",
      "Game review",
      "Flashcards",
      "Tutor",
      "Phonics"
    ],
    "scoreLabel": "Score",
    "curriculumBenefit": "Structured CEFR progression from Pre-A1 to C2, with {modules} modules and {lessonReviews} lessons and reviews."
  },
  "es": {
    "memoryTitle": "Enfoque de Hoy",
    "memoryDesc": "El Enfoque de hoy es un sistema de memoria que tiene en cuenta tus errores, metas y progreso reciente para dar forma a tu práctica diaria, de modo que dediques tiempo a lo que necesita atención.",
    "memoryDetail": "Elige una meta, como hablar con la abuela de tu esposa. El Enfoque de hoy organiza la práctica de mañana en lecciones, sesiones de tutor y tarjetas.",
    "proficiencyTitle": "Dominio del Idioma",
    "proficiencyDesc": "Desde tus primeras palabras hasta conversaciones avanzadas, sigue un curso completo del MCER con práctica que se adapta a tu capacidad.",
    "proficiencyDetail": "El MCER guía tu curso. La puntuación mide tu capacidad global de 0 a 100. Cada respuesta evaluada, su dificultad y la ayuda que necesitas ajustan el siguiente reto.",
    "companionDesc": "Crea un hábito de práctica con un compañero que crece cuando vuelves. Las metas diarias lo mantienen saludable y te dan una razón para regresar.",
    "connectedTitle": "Aprendizaje entre Plataformas",
    "connectedDesc": "El aprendizaje entre plataformas con Robots Building Education, una plataforma de programación, te permite ser dueño de tu historial y logros, crear equipos entre apps y crear becas a través del aprendizaje.",
    "immersionDesc": "Lleva el idioma fuera de la app con tareas diarias del mundo real adaptadas a tu capacidad actual.",
    "modules": "Módulos",
    "lessonReviews": "Lecciones y repasos",
    "modes": "Modos de práctica",
    "vocabularyCards": "Tarjetas de vocabulario",
    "modeNames": [
      "Vocabulario",
      "Gramática",
      "Lectura",
      "Historias",
      "Conversación",
      "Repaso en juego",
      "Tarjetas",
      "Tutor",
      "Fonética"
    ],
    "scoreLabel": "Puntuación",
    "curriculumBenefit": "Progresión MCER estructurada de Pre-A1 a C2, con {modules} módulos y {lessonReviews} lecciones y repasos."
  },
  "pt": {
    "memoryTitle": "Foco de Hoje",
    "memoryDesc": "O Foco de hoje é um sistema de memória que considera seus erros, metas e progresso recente para moldar sua prática diária, para que você dedique tempo ao que precisa de atenção.",
    "memoryDetail": "Defina uma meta, como conversar com a avó da sua esposa. O Foco de Hoje organiza a prática de amanhã em lições, sessões com tutor e flashcards.",
    "proficiencyTitle": "Proficiência",
    "proficiencyDesc": "Das primeiras palavras às conversas avançadas, siga um curso completo do QECR com prática que se adapta à sua capacidade.",
    "proficiencyDetail": "O QECR orienta seu curso. A pontuação mede sua capacidade geral de 0 a 100. Cada resposta avaliada, sua dificuldade e a ajuda necessária ajustam o próximo desafio.",
    "companionDesc": "Crie um hábito de prática com um companheiro que cresce quando você volta. As metas diárias o mantêm saudável e dão um motivo para retornar.",
    "connectedTitle": "Aprendizado entre Plataformas",
    "connectedDesc": "O aprendizado entre plataformas com Robots Building Education, uma plataforma de programação, permite ser dono do seu histórico e conquistas, criar equipes entre apps e gerar bolsas por meio do aprendizado.",
    "immersionDesc": "Leve o idioma além do app com tarefas diárias do mundo real adaptadas à sua capacidade atual.",
    "modules": "Módulos",
    "lessonReviews": "Lições e revisões",
    "modes": "Modos de prática",
    "vocabularyCards": "Cartões de vocabulário",
    "modeNames": [
      "Vocabulário",
      "Gramática",
      "Leitura",
      "Histórias",
      "Conversa",
      "Revisão em jogo",
      "Flashcards",
      "Tutor",
      "Fonética"
    ],
    "scoreLabel": "Pontuação",
    "curriculumBenefit": "Progressão QECR estruturada de Pre-A1 a C2, com {modules} módulos e {lessonReviews} lições e revisões."
  },
  "fr": {
    "memoryTitle": "Focus du Jour",
    "memoryDesc": "Le focus du jour est un système de mémoire qui tient compte de vos erreurs, objectifs et progrès récents pour façonner votre pratique quotidienne et consacrer du temps à ce qui demande votre attention.",
    "memoryDetail": "Fixez un objectif, comme parler avec la grand-mère de votre femme. Le Focus du jour organise la pratique de demain en leçons, séances avec le tuteur et cartes mémoire.",
    "proficiencyTitle": "Maîtrise de la Langue",
    "proficiencyDesc": "Des premiers mots aux conversations avancées, suivez un parcours complet du CECR avec des exercices adaptés à vos capacités.",
    "proficiencyDetail": "Le CECR guide votre parcours. Le score mesure votre capacité globale de 0 à 100. Chaque réponse évaluée, sa difficulté et l’aide nécessaire ajustent le prochain défi.",
    "companionDesc": "Créez une habitude avec un compagnon qui grandit à chaque retour. Les objectifs quotidiens le gardent en forme et vous donnent envie de revenir.",
    "connectedTitle": "Apprentissage entre Plateformes",
    "connectedDesc": "Avec Robots Building Education, une plateforme de programmation, l’apprentissage entre plateformes vous permet de posséder votre parcours et vos réussites, de créer des équipes entre applications et de financer des bourses grâce à l’apprentissage.",
    "immersionDesc": "Pratiquez au-delà de l’application avec des tâches quotidiennes du monde réel adaptées à vos capacités actuelles.",
    "modules": "Modules",
    "lessonReviews": "Leçons et révisions",
    "modes": "Modes de pratique",
    "vocabularyCards": "Cartes de vocabulaire",
    "modeNames": [
      "Vocabulaire",
      "Grammaire",
      "Lecture",
      "Histoires",
      "Conversation",
      "Révision en jeu",
      "Cartes mémoire",
      "Tuteur",
      "Phonétique"
    ],
    "scoreLabel": "Score",
    "curriculumBenefit": "Un parcours CECR structuré de Pre-A1 à C2, avec {modules} modules et {lessonReviews} leçons et révisions."
  },
  "it": {
    "memoryTitle": "Focus di Oggi",
    "memoryDesc": "Il focus di oggi è un sistema di memoria che tiene conto dei tuoi errori, obiettivi e progressi recenti per organizzare la pratica quotidiana, così dedichi tempo a ciò che richiede attenzione.",
    "memoryDetail": "Scegli un obiettivo, come parlare con la nonna di tua moglie. Il Focus di Oggi organizza la pratica di domani in lezioni, sessioni con il tutor e flashcard.",
    "proficiencyTitle": "Padronanza della Lingua",
    "proficiencyDesc": "Dalle prime parole alle conversazioni avanzate, segui un corso QCER completo con pratica che si adatta alle tue capacità.",
    "proficiencyDetail": "Il QCER guida il corso. Il punteggio misura le capacità complessive da 0 a 100. Ogni risposta valutata, la difficoltà e l’aiuto necessario regolano la prossima sfida.",
    "companionDesc": "Crea un’abitudine con un compagno che cresce quando torni. Gli obiettivi quotidiani lo tengono in salute e ti danno un motivo per tornare.",
    "connectedTitle": "Apprendimento tra Piattaforme",
    "connectedDesc": "L’apprendimento tra piattaforme con Robots Building Education, una piattaforma di programmazione, ti permette di possedere il tuo percorso e i tuoi traguardi, creare squadre tra app e creare borse di studio attraverso l’apprendimento.",
    "immersionDesc": "Porta la lingua fuori dall’app con attività quotidiane nel mondo reale adatte alle tue capacità attuali.",
    "modules": "Moduli",
    "lessonReviews": "Lezioni e ripassi",
    "modes": "Modalità di pratica",
    "vocabularyCards": "Schede di vocabolario",
    "modeNames": [
      "Vocabolario",
      "Grammatica",
      "Lettura",
      "Storie",
      "Conversazione",
      "Ripasso nel gioco",
      "Flashcard",
      "Tutor",
      "Fonetica"
    ],
    "scoreLabel": "Punteggio",
    "curriculumBenefit": "Progressione QCER strutturata da Pre-A1 a C2, con {modules} moduli e {lessonReviews} lezioni e ripassi."
  },
  "de": {
    "memoryTitle": "Tagesfokus",
    "memoryDesc": "Der Tagesfokus ist ein Gedächtnissystem, das deine Fehler, Ziele und letzten Fortschritte berücksichtigt und daraus deine tägliche Übung gestaltet, damit du an dem arbeitest, was Aufmerksamkeit braucht.",
    "memoryDetail": "Setze dir ein Ziel, etwa mit der Oma deiner Frau zu sprechen. Der Tagesfokus organisiert deine Übungen für morgen in Lektionen, Tutor-Sitzungen und Karteikarten.",
    "proficiencyTitle": "Sprachkompetenz",
    "proficiencyDesc": "Von den ersten Wörtern bis zu fortgeschrittenen Gesprächen: ein vollständiger GER-Kurs mit Übungen, die sich deinem Können anpassen.",
    "proficiencyDetail": "Der GER leitet deinen Kurs. Der Score zeigt dein Gesamtvermögen von 0 bis 100. Jede bewertete Antwort, ihre Schwierigkeit und benötigte Hilfe bestimmen die nächste Herausforderung.",
    "companionDesc": "Entwickle eine feste Übungsroutine mit einem Begleiter, der bei jedem Besuch wächst. Tagesziele halten ihn gesund und geben dir einen Grund zurückzukommen.",
    "connectedTitle": "Plattformübergreifendes Lernen",
    "connectedDesc": "Mit der Programmierplattform Robots Building Education gehört dir dein Lernnachweis samt Erfolgen. Du kannst Teams über mehrere Apps hinweg bilden und durch Lernen Stipendien schaffen.",
    "immersionDesc": "Übe außerhalb der App mit täglichen Aufgaben im echten Leben, die zu deinem aktuellen Können passen.",
    "modules": "Module",
    "lessonReviews": "Lektionen und Wiederholungen",
    "modes": "Übungsmodi",
    "vocabularyCards": "Vokabelkarten",
    "modeNames": [
      "Wortschatz",
      "Grammatik",
      "Lesen",
      "Geschichten",
      "Gespräche",
      "Spielerischer Rückblick",
      "Karteikarten",
      "Tutor",
      "Phonetik"
    ],
    "scoreLabel": "Score",
    "curriculumBenefit": "Strukturierter GER-Lernweg von Pre-A1 bis C2, mit {modules} Modulen und {lessonReviews} Lektionen und Wiederholungen."
  },
  "ja": {
    "memoryTitle": "今日のフォーカス",
    "memoryDesc": "今日のフォーカスは、間違い、目標、最近の進歩を記憶して毎日の練習を組み立てるシステムです。必要なことに時間を使えるようにします。",
    "memoryDetail": "妻の祖母と話すなど、目標を決めましょう。今日のフォーカスが、明日の練習をレッスン、チューターとの練習、フラッシュカードに整理します。",
    "proficiencyTitle": "言語の習熟度",
    "proficiencyDesc": "最初の単語から高度な会話まで、能力に合わせた練習でCEFRの学習コースを進めます。",
    "proficiencyDetail": "CEFRが学習の道筋を示します。スコアは総合的な能力を0から100で表します。各回答の評価、難易度、必要なサポートが次の課題を調整します。",
    "companionDesc": "練習するたびに育つ仲間と習慣を作りましょう。毎日の目標で仲間を元気にし、また練習したくなるきっかけを作ります。",
    "connectedTitle": "プラットフォームをまたぐ学習",
    "connectedDesc": "プログラミング学習プラットフォームのRobots Building Educationとつながり、学習記録と実績を自分で所有し、アプリをまたぐチームを作り、学習を通じて奨学金を生み出せます。",
    "immersionDesc": "アプリの外でも、現在の能力に合わせた毎日の実生活タスクで言語を使います。",
    "modules": "モジュール",
    "lessonReviews": "レッスンと復習",
    "modes": "練習モード",
    "vocabularyCards": "語彙カード",
    "modeNames": [
      "語彙",
      "文法",
      "読解",
      "物語",
      "会話",
      "ゲームで復習",
      "フラッシュカード",
      "チューター",
      "フォニックス"
    ],
    "scoreLabel": "スコア",
    "curriculumBenefit": "Pre-A1からC2までのCEFR学習パス。{modules}モジュールと{lessonReviews}のレッスン・復習。"
  },
  "zh": {
    "memoryTitle": "今日重点",
    "memoryDesc": "今日重点是一个记忆系统，会结合你的错误、目标和最近的进步来安排每日练习，让你把时间用在需要加强的地方。",
    "memoryDetail": "设定一个目标，比如和你妻子的奶奶聊天。今日重点会把明天的练习安排成课程、导师会话和闪卡。",
    "proficiencyTitle": "语言熟练度",
    "proficiencyDesc": "从第一句话到高级会话，沿着完整的CEFR课程学习，练习随你的能力调整。",
    "proficiencyDetail": "CEFR指引课程路径。分数用0到100表示整体能力。每次回答的评分、难度和所需帮助都会调整下一项挑战。",
    "companionDesc": "和每次练习都会成长的伙伴一起养成习惯。每日目标让伙伴保持健康，也给你再次练习的理由。",
    "connectedTitle": "跨平台学习",
    "connectedDesc": "与编程平台Robots Building Education连接的跨平台学习，让你拥有自己的学习记录和成就，跨应用建立团队，并通过学习创建奖学金。",
    "immersionDesc": "走出应用，通过适合当前能力的每日真实生活任务使用语言。",
    "modules": "模块",
    "lessonReviews": "课程与复习",
    "modes": "练习模式",
    "vocabularyCards": "词汇卡片",
    "modeNames": [
      "词汇",
      "语法",
      "阅读",
      "故事",
      "对话",
      "游戏复习",
      "闪卡",
      "导师",
      "自然拼读"
    ],
    "scoreLabel": "分数",
    "curriculumBenefit": "从Pre-A1到C2的CEFR学习路径，包含{modules}个模块和{lessonReviews}节课程与复习。"
  },
  "hi": {
    "memoryTitle": "आज का फ़ोकस",
    "memoryDesc": "आज का फ़ोकस एक मेमोरी प्रणाली है जो आपकी गलतियों, लक्ष्यों और हाल की प्रगति को ध्यान में रखकर रोज़ का अभ्यास तय करती है, ताकि आपका समय ज़रूरी कौशल पर लगे।",
    "memoryDetail": "अपनी पत्नी की दादी से बात करने जैसा लक्ष्य तय करें। आज का फ़ोकस कल के अभ्यास को पाठों, ट्यूटर सत्रों और फ़्लैशकार्ड में व्यवस्थित करता है।",
    "proficiencyTitle": "भाषा दक्षता",
    "proficiencyDesc": "पहले शब्दों से उन्नत बातचीत तक, अपनी क्षमता के अनुसार बदलते अभ्यास के साथ पूरा CEFR पाठ्यक्रम अपनाएँ।",
    "proficiencyDetail": "CEFR पाठ्यक्रम का रास्ता दिखाता है। स्कोर समग्र क्षमता को 0 से 100 तक दर्शाता है। हर मूल्यांकित उत्तर, उसकी कठिनाई और ज़रूरी मदद अगली चुनौती को ढालते हैं।",
    "companionDesc": "अभ्यास की आदत बनाएँ, ऐसे साथी के साथ जो आपके लौटने पर बढ़ता है। रोज़ के लक्ष्य उसे स्वस्थ रखते हैं और वापस आने की वजह देते हैं।",
    "connectedTitle": "प्लेटफ़ॉर्मों के बीच सीखना",
    "connectedDesc": "कोडिंग प्लेटफ़ॉर्म Robots Building Education के साथ जुड़े सीखने से आप अपने सीखने के रिकॉर्ड और उपलब्धियों के मालिक बन सकते हैं, ऐप्स के बीच टीम बना सकते हैं और सीखने के ज़रिए छात्रवृत्तियाँ बना सकते हैं।",
    "immersionDesc": "ऐप से बाहर रोज़मर्रा की वास्तविक गतिविधियों से भाषा का अभ्यास करें, जो आपकी वर्तमान क्षमता के अनुसार हों।",
    "modules": "मॉड्यूल",
    "lessonReviews": "पाठ और दोहराव",
    "modes": "अभ्यास के तरीके",
    "vocabularyCards": "शब्दावली कार्ड",
    "modeNames": [
      "शब्दावली",
      "व्याकरण",
      "पठन",
      "कहानियाँ",
      "बातचीत",
      "खेल में दोहराव",
      "फ़्लैशकार्ड",
      "ट्यूटर",
      "ध्वनिकी"
    ],
    "scoreLabel": "स्कोर",
    "curriculumBenefit": "Pre-A1 से C2 तक व्यवस्थित CEFR प्रगति, {modules} मॉड्यूल और {lessonReviews} पाठों व दोहराव के साथ।"
  },
  "ar": {
    "memoryTitle": "تركيز النهارده",
    "memoryDesc": "تركيز النهارده هو نظام ذاكرة بياخد في الاعتبار أخطاءك وأهدافك وتقدمك الأخير عشان يشكل تدريبك اليومي، فتقضي وقتك على اللي محتاج اهتمام.",
    "memoryDetail": "حدد هدف، زي إنك تتكلم مع جدة مراتك. تركيز اليوم بينظم تدريب بكرة في دروس وجلسات مع المدرس وبطاقات مراجعة.",
    "proficiencyTitle": "إتقان اللغة",
    "proficiencyDesc": "من أول كلماتك لحد المحادثات المتقدمة، اتبع كورس CEFR كامل بتدريب بيتكيف مع قدرتك.",
    "proficiencyDetail": "CEFR بيحدد مسار الكورس. الدرجة بتقيس قدرتك العامة من 0 لـ100. كل إجابة متقيّمة وصعوبتها والمساعدة اللي محتاجها بيضبطوا التحدي اللي بعده.",
    "companionDesc": "ابني عادة تدريب مع رفيق بيكبر كل ما ترجع. الأهداف اليومية بتحافظ على صحته وبتديك سبب ترجع تتمرن.",
    "connectedTitle": "تعلم عبر المنصات",
    "connectedDesc": "التعلم عبر المنصات مع Robots Building Education، منصة لتعلم البرمجة، بيخليك تملك سجل تعلمك وإنجازاتك، وتكوّن فرق بين التطبيقات، وتخلق منح من خلال التعلم.",
    "immersionDesc": "استخدم اللغة خارج التطبيق بمهام يومية من الحياة الحقيقية مناسبة لقدراتك الحالية.",
    "modules": "وحدات",
    "lessonReviews": "دروس ومراجعات",
    "modes": "أوضاع التدريب",
    "vocabularyCards": "بطاقات مفردات",
    "modeNames": [
      "مفردات",
      "قواعد",
      "قراءة",
      "قصص",
      "محادثة",
      "مراجعة باللعب",
      "بطاقات",
      "مدرس",
      "الصوتيات"
    ],
    "scoreLabel": "الدرجة",
    "curriculumBenefit": "مسار CEFR من Pre-A1 لحد C2، فيه {modules} وحدة و{lessonReviews} درس ومراجعة."
  }
};
