export const SUBSCRIPTION_KEY_REPLACEMENT_REQUIRED_KEYS = [
  "eyebrow",
  "title",
  "body",
  "reassurance",
  "confirm",
  "cancel",
  "replacing",
  "failed",
  "membershipInactive",
  "unavailable",
];

export const SUBSCRIPTION_KEY_REPLACEMENT_COPY = {
  en: {
    eyebrow: "Membership access",
    title: "Replace your previous Piyali key?",
    body: "This Patreon membership is already linked to another Piyali key. You can move membership access to the key currently open in this app. The previous key will lose membership access.",
    reassurance: "Only membership access moves. Your learning data remains attached to each Piyali key.",
    confirm: "Replace previous key",
    cancel: "Cancel",
    replacing: "Replacing key",
    failed: "We couldn't replace the linked key. Please restart Patreon login.",
    membershipInactive: "We couldn't find an active paid membership for this Patreon account.",
    unavailable: "Patreon is temporarily unavailable. Please try again.",
  },
  es: {
    eyebrow: "Acceso de membresía",
    title: "¿Reemplazar tu clave de Piyali anterior?",
    body: "Esta membresía de Patreon ya está vinculada a otra clave de Piyali. Puedes mover el acceso de membresía a la clave abierta actualmente en esta app. La clave anterior perderá el acceso de membresía.",
    reassurance: "Solo se mueve el acceso de membresía. Tus datos de aprendizaje permanecen vinculados a cada clave de Piyali.",
    confirm: "Reemplazar clave anterior",
    cancel: "Cancelar",
    replacing: "Reemplazando clave",
    failed: "No pudimos reemplazar la clave vinculada. Reinicia el acceso con Patreon.",
    membershipInactive: "No encontramos una membresía de pago activa para esta cuenta de Patreon.",
    unavailable: "Patreon no está disponible temporalmente. Inténtalo de nuevo.",
  },
  pt: {
    eyebrow: "Acesso da assinatura",
    title: "Substituir sua chave Piyali anterior?",
    body: "Esta assinatura do Patreon já está vinculada a outra chave Piyali. Você pode mover o acesso da assinatura para a chave aberta agora neste app. A chave anterior perderá o acesso da assinatura.",
    reassurance: "Somente o acesso da assinatura é movido. Seus dados de aprendizagem continuam vinculados a cada chave Piyali.",
    confirm: "Substituir chave anterior",
    cancel: "Cancelar",
    replacing: "Substituindo chave",
    failed: "Não foi possível substituir a chave vinculada. Reinicie o login do Patreon.",
    membershipInactive: "Não encontramos uma assinatura paga ativa para esta conta do Patreon.",
    unavailable: "O Patreon está temporariamente indisponível. Tente novamente.",
  },
  it: {
    eyebrow: "Accesso all'abbonamento",
    title: "Sostituire la chiave Piyali precedente?",
    body: "Questo abbonamento Patreon è già collegato a un'altra chiave Piyali. Puoi spostare l'accesso all'abbonamento sulla chiave attualmente aperta nell'app. La chiave precedente perderà l'accesso.",
    reassurance: "Viene spostato solo l'accesso all'abbonamento. I dati di apprendimento restano associati a ciascuna chiave Piyali.",
    confirm: "Sostituisci chiave precedente",
    cancel: "Annulla",
    replacing: "Sostituzione chiave",
    failed: "Impossibile sostituire la chiave collegata. Riavvia l'accesso Patreon.",
    membershipInactive: "Non abbiamo trovato un abbonamento a pagamento attivo per questo account Patreon.",
    unavailable: "Patreon non è temporaneamente disponibile. Riprova.",
  },
  fr: {
    eyebrow: "Accès membre",
    title: "Remplacer votre ancienne clé Piyali ?",
    body: "Cet abonnement Patreon est déjà lié à une autre clé Piyali. Vous pouvez transférer l'accès membre vers la clé actuellement ouverte dans l'appli. L'ancienne clé perdra cet accès.",
    reassurance: "Seul l'accès membre est transféré. Vos données d'apprentissage restent associées à chaque clé Piyali.",
    confirm: "Remplacer l'ancienne clé",
    cancel: "Annuler",
    replacing: "Remplacement de la clé",
    failed: "Impossible de remplacer la clé liée. Recommencez la connexion Patreon.",
    membershipInactive: "Nous n'avons trouvé aucun abonnement payant actif pour ce compte Patreon.",
    unavailable: "Patreon est temporairement indisponible. Réessayez.",
  },
  de: {
    eyebrow: "Mitgliedszugang",
    title: "Vorherigen Piyali-Schlüssel ersetzen?",
    body: "Diese Patreon-Mitgliedschaft ist bereits mit einem anderen Piyali-Schlüssel verbunden. Du kannst den Mitgliedszugang auf den aktuell geöffneten Schlüssel übertragen. Der vorherige Schlüssel verliert diesen Zugang.",
    reassurance: "Nur der Mitgliedszugang wird übertragen. Deine Lerndaten bleiben mit dem jeweiligen Piyali-Schlüssel verbunden.",
    confirm: "Vorherigen Schlüssel ersetzen",
    cancel: "Abbrechen",
    replacing: "Schlüssel wird ersetzt",
    failed: "Der verknüpfte Schlüssel konnte nicht ersetzt werden. Starte die Patreon-Anmeldung neu.",
    membershipInactive: "Für dieses Patreon-Konto wurde keine aktive bezahlte Mitgliedschaft gefunden.",
    unavailable: "Patreon ist vorübergehend nicht verfügbar. Bitte versuche es erneut.",
  },
  ja: {
    eyebrow: "メンバーアクセス",
    title: "以前のPiyaliキーを置き換えますか？",
    body: "このPatreonメンバーシップは別のPiyaliキーに接続されています。メンバーアクセスを現在このアプリで開いているキーへ移動できます。以前のキーはメンバーアクセスを失います。",
    reassurance: "移動するのはメンバーアクセスのみです。学習データはそれぞれのPiyaliキーに紐づいたままです。",
    confirm: "以前のキーを置き換える",
    cancel: "キャンセル",
    replacing: "キーを置き換えています",
    failed: "接続済みキーを置き換えられませんでした。Patreonログインをやり直してください。",
    membershipInactive: "このPatreonアカウントの有効な有料メンバーシップが見つかりませんでした。",
    unavailable: "Patreonは一時的に利用できません。もう一度お試しください。",
  },
  hi: {
    eyebrow: "सदस्यता एक्सेस",
    title: "पुरानी Piyali कुंजी बदलें?",
    body: "यह Patreon सदस्यता पहले से दूसरी Piyali कुंजी से जुड़ी है। आप सदस्यता एक्सेस को इस ऐप में अभी खुली कुंजी पर ले जा सकते हैं। पुरानी कुंजी का सदस्यता एक्सेस हट जाएगा।",
    reassurance: "केवल सदस्यता एक्सेस बदलेगा। आपका सीखने का डेटा हर Piyali कुंजी से जुड़ा रहेगा।",
    confirm: "पुरानी कुंजी बदलें",
    cancel: "रद्द करें",
    replacing: "कुंजी बदली जा रही है",
    failed: "जुड़ी कुंजी बदली नहीं जा सकी। Patreon लॉगिन फिर से शुरू करें।",
    membershipInactive: "इस Patreon खाते के लिए कोई सक्रिय सशुल्क सदस्यता नहीं मिली।",
    unavailable: "Patreon अभी अस्थायी रूप से उपलब्ध नहीं है। फिर कोशिश करें।",
  },
  ar: {
    eyebrow: "وصول العضوية",
    title: "هل تريد استبدال مفتاح Piyali السابق؟",
    body: "عضوية Patreon هذه مرتبطة بمفتاح Piyali آخر. يمكنك نقل وصول العضوية إلى المفتاح المفتوح حاليًا في التطبيق. سيفقد المفتاح السابق وصول العضوية.",
    reassurance: "يتم نقل وصول العضوية فقط. تظل بيانات تعلمك مرتبطة بكل مفتاح Piyali.",
    confirm: "استبدال المفتاح السابق",
    cancel: "إلغاء",
    replacing: "جارٍ استبدال المفتاح",
    failed: "تعذر استبدال المفتاح المرتبط. أعد بدء تسجيل الدخول إلى Patreon.",
    membershipInactive: "لم نعثر على عضوية مدفوعة نشطة لحساب Patreon هذا.",
    unavailable: "Patreon غير متاح مؤقتًا. حاول مرة أخرى.",
  },
  zh: {
    eyebrow: "会员访问权限",
    title: "要替换以前的 Piyali 密钥吗？",
    body: "此 Patreon 会员已连接到另一个 Piyali 密钥。你可以将会员访问权限移至当前在应用中打开的密钥。旧密钥将失去会员访问权限。",
    reassurance: "只有会员访问权限会被转移。你的学习数据仍与各自的 Piyali 密钥关联。",
    confirm: "替换以前的密钥",
    cancel: "取消",
    replacing: "正在替换密钥",
    failed: "无法替换已连接的密钥。请重新开始 Patreon 登录。",
    membershipInactive: "未找到此 Patreon 账户的有效付费会员资格。",
    unavailable: "Patreon 暂时不可用，请重试。",
  },
};
