const en = {
  preparingAudio: "Loading",
  modes: "Story modes", speaking: "Practice", radio: "Radio", conversation: "Conversation",
  radioIntro: "Tune in to a call. Press play, record any lines for You, then answer at each break.",
  conversationIntro: "Press play to follow the conversation. Record your lines as You, then answer the question.",
  yourTurn: "Your turn to speak", speakingNow: "Speaking", record: "Record", stopRecording: "Stop", connectingMic: "Connecting",
  speechIncorrect: "Not quite. Try again.", recordingError: "Recording couldn’t complete. Check your microphone and try again.", micDenied: "Allow microphone access, then try recording again.",
  loading: "Getting your story ready…", loadingSub: "Generating your lesson content…", generationError: "We couldn’t prepare this story. Please try again.",
  audioError: "Audio couldn’t play. Tap play to try again.", retry: "Try again", play: "Play", pause: "Pause", resume: "Resume", replay: "Replay", listen: "Listen to the excerpt",
  start: "Start story", nextPair: "Next pair", check: "Submit", next: "Continue", finish: "Finish story", skip: "Skip", back: "New story",
  checkpoint: "Check your understanding", heard: "Listen to the segment to unlock the question.", showQuestion: "Answer question", correct: "That’s right!", incorrect: "Not quite. Here’s what happened:",
  translation: "Show translation", hideTranslation: "Hide translation",
  complete: "Story complete", score: "correct on the first try", saving: "Saving progress…", saveError: "Your story is complete, but progress could not be saved. Try again.",
  onAir: "ON AIR", ready: "READY TO LISTEN", paused: "PAUSED", segment: "Part", of: "of", clear: "Clear", answer: "Your answer", xp: "XP", review: "Review the answer, then continue.",
  reviewStory: "Review story", sentencesCompleted: "sentences completed",
  call: "Call", practice: "Practice", story: "Story", you: "You",
};

const es = {
  preparingAudio: "Cargando",
  modes: "Modos de historias", speaking: "Práctica", radio: "Radio", conversation: "Conversación",
  radioIntro: "Pulsa reproducir, graba las frases de tu personaje y responde en cada pausa.",
  conversationIntro: "Pulsa reproducir para seguir la conversación. Graba tus frases y luego responde la pregunta.",
  yourTurn: "Tu turno de hablar", speakingNow: "Hablando", record: "Grabar", stopRecording: "Detener", connectingMic: "Conectando",
  speechIncorrect: "Todavía no. Inténtalo de nuevo.", recordingError: "No se pudo completar la grabación. Revisa tu micrófono e inténtalo de nuevo.", micDenied: "Permite el acceso al micrófono y vuelve a grabar.",
  loading: "Preparando tu historia…", loadingSub: "Generando el contenido de tu lección…", generationError: "No pudimos preparar la historia. Inténtalo de nuevo.", audioError: "No se pudo reproducir el audio. Pulsa reproducir para reintentar.",
  retry: "Reintentar", play: "Reproducir", pause: "Pausar", resume: "Reanudar", replay: "Repetir", listen: "Escuchar el fragmento", start: "Comenzar historia", nextPair: "Siguiente par",
  check: "Comprobar", next: "Continuar", finish: "Terminar historia", skip: "Saltar", back: "Nueva historia", checkpoint: "Comprueba lo que entendiste", heard: "Escucha esta parte para desbloquear la pregunta.", showQuestion: "Responder pregunta",
  correct: "¡Correcto!", incorrect: "No exactamente. Esto es lo que pasó:", translation: "Mostrar traducción", hideTranslation: "Ocultar traducción",
  complete: "Historia completada", score: "correctas al primer intento", saving: "Guardando progreso…", saveError: "Completaste la historia, pero no se guardó el progreso. Inténtalo de nuevo.",
  onAir: "AL AIRE", ready: "LISTO PARA ESCUCHAR", paused: "EN PAUSA", segment: "Parte", of: "de", clear: "Borrar", answer: "Tu respuesta", xp: "XP", review: "Revisa la respuesta y continúa.",
  reviewStory: "Revisar historia", sentencesCompleted: "frases completadas",
  call: "Llamada", practice: "Práctica", story: "Historia", you: "Tú",
};

const fr = {
  preparingAudio: "Chargement",
  modes: "Modes d'histoire", speaking: "Pratique", radio: "Radio", conversation: "Conversation",
  radioIntro: "Écoutez un appel. Appuyez sur lecture, enregistrez vos répliques pour Toi, puis répondez à chaque pause.",
  conversationIntro: "Appuyez sur lecture pour suivre la conversation. Enregistrez vos répliques et répondez à la question.",
  yourTurn: "À vous de parler", speakingNow: "En train de parler", record: "Enregistrer", stopRecording: "Arrêter", connectingMic: "Connexion",
  speechIncorrect: "Pas tout à fait. Réessayez.", recordingError: "L'enregistrement a échoué. Vérifiez votre micro et réessayez.", micDenied: "Autorisez l'accès au micro, puis réessayez d'enregistrer.",
  loading: "Préparation de votre histoire…", loadingSub: "Génération de votre leçon…", generationError: "Impossible de préparer cette histoire. Veuillez réessayer.",
  audioError: "L'audio n'a pas pu être lu. Appuyez sur lecture pour réessayer.", retry: "Réessayer", play: "Lecture", pause: "Pause", resume: "Reprendre", replay: "Rejouer", listen: "Écouter l'extrait",
  start: "Commencer l'histoire", nextPair: "Paire suivante", check: "Valider", next: "Continuer", finish: "Terminer l'histoire", skip: "Passer", back: "Nouvelle histoire",
  checkpoint: "Vérifiez votre compréhension", heard: "Écoutez le segment pour débloquer la question.", showQuestion: "Répondre à la question", correct: "C'est exact !", incorrect: "Pas tout à fait. Voici ce qui s'est passé :",
  translation: "Afficher la traduction", hideTranslation: "Masquer la traduction",
  complete: "Histoire terminée", score: "correctes au premier essai", saving: "Enregistrement du progrès…", saveError: "Histoire terminée, mais le progrès n'a pas pu être enregistré. Réessayez.",
  onAir: "EN ONDE", ready: "PRÊT À ÉCOUTER", paused: "EN PAUSE", segment: "Partie", of: "sur", clear: "Effacer", answer: "Votre réponse", xp: "XP", review: "Revoyez la réponse, puis continuez.",
  reviewStory: "Revoir l'histoire", sentencesCompleted: "phrases terminées",
  call: "Appel", practice: "Pratique", story: "Histoire", you: "Toi",
};

const de = {
  preparingAudio: "Laden",
  modes: "Geschichtenmodi", speaking: "Übung", radio: "Radio", conversation: "Gespräch",
  radioIntro: "Höre eine Radiosendung. Drücke auf Wiedergabe, sprich deine Zeilen für Du ein und antworte bei jeder Pause.",
  conversationIntro: "Drücke auf Wiedergabe, um dem Gespräch zu folgen. Nimm deine Zeilen auf und beantworte die Frage.",
  yourTurn: "Du bist dran zu sprechen", speakingNow: "Spricht gerade", record: "Aufnehmen", stopRecording: "Stopp", connectingMic: "Verbinden",
  speechIncorrect: "Nicht ganz. Versuch es noch einmal.", recordingError: "Aufnahme fehlgeschlagen. Überprüfe dein Mikrofon und versuche es erneut.", micDenied: "Erlaube den Mikrofonzugriff und versuche es erneut.",
  loading: "Deine Geschichte wird vorbereitet…", loadingSub: "Lektionsinhalt wird generiert…", generationError: "Diese Geschichte konnte nicht vorbereitet werden. Bitte versuche es erneut.",
  audioError: "Audio konnte nicht abgespielt werden. Tippe auf Wiedergabe, um es erneut zu versuchen.", retry: "Erneut versuchen", play: "Abspielen", pause: "Pause", resume: "Fortsetzen", replay: "Wiederholen", listen: "Ausschnitt anhören",
  start: "Geschichte starten", nextPair: "Nächstes Paar", check: "Überprüfen", next: "Weiter", finish: "Geschichte beenden", skip: "Überspringen", back: "Neue Geschichte",
  checkpoint: "Verständnis prüfen", heard: "Höre den Abschnitt an, um die Frage freizuschalten.", showQuestion: "Frage beantworten", correct: "Richtig!", incorrect: "Nicht ganz. Das ist passiert:",
  translation: "Übersetzung anzeigen", hideTranslation: "Übersetzung ausblenden",
  complete: "Geschichte abgeschlossen", score: "im ersten Versuch richtig", saving: "Fortschritt wird gespeichert…", saveError: "Geschichte abgeschlossen, aber Fortschritt konnte nicht gespeichert werden. Versuche es erneut.",
  onAir: "ON AIR", ready: "BEREIT ZUM HÖREN", paused: "PAUSIERT", segment: "Teil", of: "von", clear: "Löschen", answer: "Deine Antwort", xp: "XP", review: "Sieh dir die Antwort an und fahre dann fort.",
  reviewStory: "Geschichte wiederholen", sentencesCompleted: "Sätze abgeschlossen",
  call: "Anruf", practice: "Übung", story: "Geschichte", you: "Du",
};

const it = {
  preparingAudio: "Caricamento",
  modes: "Modalità storia", speaking: "Pratica", radio: "Radio", conversation: "Conversazione",
  radioIntro: "Ascolta una chiamata. Premi play, registra le tue battute per Tu e rispondi a ogni pausa.",
  conversationIntro: "Premi play per seguire la conversazione. Registra le tue battute e rispondi alla domanda.",
  yourTurn: "Tocca a te parlare", speakingNow: "Parlando", record: "Registra", stopRecording: "Stop", connectingMic: "Connessione",
  speechIncorrect: "Non proprio. Riprova.", recordingError: "Registrazione non completata. Controlla il microfono e riprova.", micDenied: "Consenti l'accesso al microfono, poi prova a registrare di nuovo.",
  loading: "Preparazione della tua storia…", loadingSub: "Generazione della lezione…", generationError: "Non siamo riusciti a preparare questa storia. Riprova.",
  audioError: "Impossibile riprodurre l'audio. Tocca play per riprovare.", retry: "Riprova", play: "Riproduci", pause: "Pausa", resume: "Riprendi", replay: "Riascolta", listen: "Ascolta l'estratto",
  start: "Inizia storia", nextPair: "Prossima coppia", check: "Verifica", next: "Continua", finish: "Termina storia", skip: "Salta", back: "Nuova storia",
  checkpoint: "Controlla la tua comprensione", heard: "Ascolta il segmento per sbloccare la domanda.", showQuestion: "Rispondi alla domanda", correct: "Esatto!", incorrect: "Non esattamente. Ecco cosa è successo:",
  translation: "Mostra traduzione", hideTranslation: "Nascondi traduzione",
  complete: "Storia completata", score: "corrette al primo tentativo", saving: "Salvataggio progressi…", saveError: "Storia completata, ma il progresso non è stato salvato. Riprova.",
  onAir: "IN ONDA", ready: "PRONTO PER L'ASCOLTO", paused: "IN PAUSA", segment: "Parte", of: "di", clear: "Cancella", answer: "La tua risposta", xp: "XP", review: "Rivedi la risposta, poi continua.",
  reviewStory: "Rivedi la storia", sentencesCompleted: "frasi completate",
  call: "Chiamata", practice: "Pratica", story: "Storia", you: "Tu",
};

const pt = {
  preparingAudio: "Carregando",
  modes: "Modos de história", speaking: "Prática", radio: "Rádio", conversation: "Conversa",
  radioIntro: "Sintonize uma chamada. Pressione reproduzir, grave suas falas para Você e responda em cada pausa.",
  conversationIntro: "Pressione reproduzir para acompanhar a conversa. Grave suas frases e depois responda à pergunta.",
  yourTurn: "Sua vez de falar", speakingNow: "Falando", record: "Gravar", stopRecording: "Parar", connectingMic: "Conectando",
  speechIncorrect: "Quase lá. Tente novamente.", recordingError: "A gravação não pôde ser concluída. Verifique seu microfone e tente novamente.", micDenied: "Permita o acesso ao microfone e tente gravar novamente.",
  loading: "Preparando sua história…", loadingSub: "Gerando sua lição…", generationError: "Não conseguimos preparar esta história. Tente novamente.",
  audioError: "O áudio não pôde ser reproduzido. Toque em reproduzir para tentar novamente.", retry: "Tentar novamente", play: "Reproduzir", pause: "Pausar", resume: "Retomar", replay: "Repetir", listen: "Ouvir o trecho",
  start: "Começar história", nextPair: "Próximo par", check: "Enviar", next: "Continuar", finish: "Terminar história", skip: "Pular", back: "Nova história",
  checkpoint: "Verifique sua compreensão", heard: "Ouça o segmento para desbloquear a pergunta.", showQuestion: "Responder à pergunta", correct: "Correto!", incorrect: "Não exatamente. Aqui está o que aconteceu:",
  translation: "Mostrar tradução", hideTranslation: "Ocultar tradução",
  complete: "História concluída", score: "corretas na primeira tentativa", saving: "Salvando progresso…", saveError: "Sua história está completa, mas o progresso não pôde ser salvo. Tente novamente.",
  onAir: "NO AR", ready: "PRONTO PARA OUVIR", paused: "PAUSADO", segment: "Parte", of: "de", clear: "Limpar", answer: "Sua resposta", xp: "XP", review: "Revise a resposta e continue.",
  reviewStory: "Revisar história", sentencesCompleted: "frases concluídas",
  call: "Chamada", practice: "Prática", story: "História", you: "Você",
};

const ja = {
  preparingAudio: "読み込み中",
  modes: "ストーリーモード", speaking: "練習", radio: "ラジオ", conversation: "会話",
  radioIntro: "電話番組を聞きましょう。再生を押し、あなたのセリフを録音し、区切りごとに質問に答えてください。",
  conversationIntro: "再生を押して会話を聞きましょう。セリフを録音してから、質問に答えてください。",
  yourTurn: "あなたの話す番です", speakingNow: "発話中", record: "録音", stopRecording: "停止", connectingMic: "接続中",
  speechIncorrect: "惜しい！もう一度試してください。", recordingError: "録音を完了できませんでした。マイクを確認して再試行してください。", micDenied: "マイクへのアクセスを許可して、再度録音してください。",
  loading: "ストーリーを準備中…", loadingSub: "レッスンの内容を生成中…", generationError: "ストーリーを準備できませんでした。もう一度お試しください。",
  audioError: "音声を再生できませんでした。再生をタップして再試行してください。", retry: "もう一度試す", play: "再生", pause: "一時停止", resume: "再開", replay: "もう一度再生", listen: "抜粋を聞く",
  start: "ストーリーを始める", nextPair: "次のペア", check: "回答する", next: "続ける", finish: "ストーリーを完了", skip: "スキップ", back: "新しいストーリー",
  checkpoint: "理解度チェック", heard: "セグメントを聞いて質問を解除してください。", showQuestion: "質問に答える", correct: "正解です！", incorrect: "不正解です。解説はこちら：",
  translation: "翻訳を表示", hideTranslation: "翻訳を非表示",
  complete: "ストーリー完了", score: "1回目で正解", saving: "進行状況を保存中…", saveError: "ストーリーは完了しましたが、保存できませんでした。もう一度お試しください。",
  onAir: "放送中", ready: "聴取準備完了", paused: "一時停止中", segment: "パート", of: "/", clear: "クリア", answer: "あなたの回答", xp: "XP", review: "回答を確認して次に進んでください。",
  reviewStory: "ストーリーを確認", sentencesCompleted: "文完了",
  call: "通話", practice: "練習", story: "ストーリー", you: "あなた",
};

const ru = {
  preparingAudio: "Загрузка",
  modes: "Режимы историй", speaking: "Практика", radio: "Радио", conversation: "Разговор",
  radioIntro: "Послушайте звонок. Нажмите воспроизведение, запишите фразы за Ты и отвечайте на вопросы на паузах.",
  conversationIntro: "Нажмите воспроизведение, чтобы следить за разговором. Запишите свои фразы и ответьте на вопрос.",
  yourTurn: "Ваша очередь говорить", speakingNow: "Говорит", record: "Запись", stopRecording: "Стоп", connectingMic: "Подключение",
  speechIncorrect: "Не совсем. Попробуйте ещё раз.", recordingError: "Не удалось завершить запись. Проверьте микрофон и попробуйте снова.", micDenied: "Разрешите доступ к микрофону и попробуйте записать снова.",
  loading: "Готовим вашу историю…", loadingSub: "Создаем урок…", generationError: "Не удалось подготовить историю. Попробуйте снова.",
  audioError: "Не удалось воспроизвести аудио. Нажмите воспроизведение, чтобы повторить.", retry: "Попробовать снова", play: "Воспроизвести", pause: "Пауза", resume: "Продолжить", replay: "Повторить", listen: "Прослушать фрагмент",
  start: "Начать историю", nextPair: "Следующая пара", check: "Проверить", next: "Далее", finish: "Завершить историю", skip: "Пропустить", back: "Новая история",
  checkpoint: "Проверьте понимание", heard: "Прослушайте фрагмент, чтобы открыть вопрос.", showQuestion: "Ответить на вопрос", correct: "Верно!", incorrect: "Не совсем. Вот что произошло:",
  translation: "Показать перевод", hideTranslation: "Скрыть перевод",
  complete: "История завершена", score: "правильно с первой попытки", saving: "Сохранение прогресса…", saveError: "История завершена, но прогресс не сохранился. Попробуйте снова.",
  onAir: "В ЭФИРЕ", ready: "ГОТОВО К ПРОСЛУШИВАНИЮ", paused: "НА ПАУЗЕ", segment: "Часть", of: "из", clear: "Очистить", answer: "Ваш ответ", xp: "XP", review: "Проверьте ответ и продолжайте.",
  reviewStory: "Повторить историю", sentencesCompleted: "предложений завершено",
  call: "Звонок", practice: "Практика", story: "История", you: "Ты",
};

const el = {
  preparingAudio: "Φόρτωση",
  modes: "Λειτουργίες ιστορίας", speaking: "Εξάσκηση", radio: "Ραδιόφωνο", conversation: "Συνομιλία",
  radioIntro: "Ακούστε μια κλήση. Πατήστε αναπαραγωγή, ηχογραφήστε τις ατάκες σας για Εσύ και απαντήστε σε κάθε διακοπή.",
  conversationIntro: "Πατήστε αναπαραγωγή για να παρακολουθήσετε τη συνομιλία. Ηχογραφήστε τις ατάκες σας και απαντήστε στην ερώτηση.",
  yourTurn: "Η σειρά σας να μιλήσετε", speakingNow: "Μιλάει", record: "Εγγραφή", stopRecording: "Διακοπή", connectingMic: "Σύνδεση",
  speechIncorrect: "Όχι ακριβώς. Δοκιμάστε ξανά.", recordingError: "Η εγγραφή δεν ολοκληρώθηκε. Ελέγξτε το μικρόφωνό σας και προσπαθήστε ξανά.", micDenied: "Επιτρέψτε την πρόσβαση στο μικρόφωνο και δοκιμάστε ξανά.",
  loading: "Προετοιμασία της ιστορίας σας…", loadingSub: "Δημιουργία του μαθήματος…", generationError: "Δεν μπορέσαμε να προετοιμάσουμε αυτήν την ιστορία. Προσπαθήστε ξανά.",
  audioError: "Δεν ήταν δυνατή η αναπαραγωγή ήχου. Πατήστε αναπαραγωγή για να δοκιμάσετε ξανά.", retry: "Δοκιμάστε ξανά", play: "Αναπαραγωγή", pause: "Παύση", resume: "Συνέχιση", replay: "Επανάληψη", listen: "Ακούστε το απόσπασμα",
  start: "Έναρξη ιστορίας", nextPair: "Επόμενο ζεύγος", check: "Υποβολή", next: "Συνέχεια", finish: "Ολοκλήρωση ιστορίας", skip: "Παράλειψη", back: "Νέα ιστορία",
  checkpoint: "Ελέγξτε την κατανόησή σας", heard: "Ακούστε το απόσπασμα για να ξεκλειδώσετε την ερώτηση.", showQuestion: "Απάντηση στην ερώτηση", correct: "Σωστά!", incorrect: "Όχι ακριβώς. Να τι συνέβη:",
  translation: "Εμφάνιση μετάφρασης", hideTranslation: "Απόκρυψη μετάφρασης",
  complete: "Η ιστορία ολοκληρώθηκε", score: "σωστά με την πρώτη προσπάθεια", saving: "Αποθήκευση προόδου…", saveError: "Η ιστορία ολοκληρώθηκε, αλλά η πρόοδος δεν αποθηκεύτηκε. Δοκιμάστε ξανά.",
  onAir: "ΣΤΟΝ ΑΕΡΑ", ready: "ΕΤΟΙΜΟ ΓΙΑ ΑΚΡΟΑΣΗ", paused: "ΣΕ ΠΑΥΣΗ", segment: "Μέρος", of: "από", clear: "Εκκαθάριση", answer: "Η απάντησή σας", xp: "XP", review: "Ελέγξτε την απάντηση και συνεχίστε.",
  reviewStory: "Ανασκόπηση ιστορίας", sentencesCompleted: "προτάσεις ολοκληρώθηκαν",
  call: "Κλήση", practice: "Εξάσκηση", story: "Ιστορία", you: "Εσύ",
};

const nl = {
  preparingAudio: "Laden",
  modes: "Verhaalmodi", speaking: "Oefening", radio: "Radio", conversation: "Gesprek",
  radioIntro: "Luister naar een oproep. Druk op afspelen, spreek je regels in voor Jij en antwoord bij elke pauze.",
  conversationIntro: "Druk op afspelen om het gesprek te volgen. Neem je zinnen op en beantwoord de vraag.",
  yourTurn: "Jouw beurt om te praten", speakingNow: "Aan het woord", record: "Opnemen", stopRecording: "Stop", connectingMic: "Verbinden",
  speechIncorrect: "Niet helemaal. Probeer het opnieuw.", recordingError: "Opname kon niet worden voltooid. Controleer je microfoon en probeer het opnieuw.", micDenied: "Geef toegang tot de microfoon en probeer opnieuw op te nemen.",
  loading: "Je verhaal klaarmaken…", loadingSub: "Lesinhoud genereren…", generationError: "We konden dit verhaal niet voorbereiden. Probeer het opnieuw.",
  audioError: "Audio kon niet worden afgespeeld. Tik op afspelen om opnieuw te proberen.", retry: "Opnieuw proberen", play: "Afspelen", pause: "Pauzeren", resume: "Hervatten", replay: "Herhalen", listen: "Luister naar het fragment",
  start: "Start verhaal", nextPair: "Volgend paar", check: "Controleren", next: "Doorgaan", finish: "Verhaal afronden", skip: "Overslaan", back: "Nieuw verhaal",
  checkpoint: "Controleer je begrip", heard: "Luister naar het deel om de vraag te ontgrendelen.", showQuestion: "Vraag beantwoorden", correct: "Helemaal juist!", incorrect: "Niet helemaal. Dit is wat er gebeurde:",
  translation: "Vertaling tonen", hideTranslation: "Vertaling verbergen",
  complete: "Verhaal voltooid", score: "correct bij de eerste poging", saving: "Voortgang opslaan…", saveError: "Je verhaal is klaar, maar de voortgang kon niet worden opgeslagen. Probeer het opnieuw.",
  onAir: "ON AIR", ready: "KLAAR OM TE LUISTEREN", paused: "GEPAUZEERD", segment: "Deel", of: "van", clear: "Wissen", answer: "Jouw antwoord", xp: "XP", review: "Bekijk het antwoord en ga door.",
  reviewStory: "Verhaal bekijken", sentencesCompleted: "zinnen voltooid",
  call: "Oproep", practice: "Oefening", story: "Verhaal", you: "Jij",
};

const pl = {
  preparingAudio: "Ładowanie",
  modes: "Tryby historii", speaking: "Praktyka", radio: "Radio", conversation: "Rozmowa",
  radioIntro: "Posłuchaj połączenia. Naciśnij odtwarzaj, nagraj kwestie dla Ty i odpowiedz przy każdej przerwie.",
  conversationIntro: "Naciśnij odtwarzaj, aby śledzić rozmowę. Nagraj swoje kwestie i odpowiedz na pytanie.",
  yourTurn: "Twoja kolej na mowę", speakingNow: "Mówi", record: "Nagraj", stopRecording: "Zatrzymaj", connectingMic: "Łączenie",
  speechIncorrect: "Nie do końca. Spróbuj ponownie.", recordingError: "Nie udało się dokończyć nagrania. Sprawdź mikrofon i spróbuj ponownie.", micDenied: "Zezwól na dostęp do mikrofonu i spróbuj nagrać ponownie.",
  loading: "Przygotowywanie Twojej historii…", loadingSub: "Generowanie lekcji…", generationError: "Nie udało się przygotować tej historii. Spróbuj ponownie.",
  audioError: "Nie udało się odtworzyć dźwięku. Stuknij odtwórz, aby spróbować ponownie.", retry: "Spróbuj ponownie", play: "Odtwórz", pause: "Wstrzymaj", resume: "Wznów", replay: "Powtórz", listen: "Posłuchaj fragmentu",
  start: "Rozpocznij historię", nextPair: "Następna para", check: "Sprawdź", next: "Kontynuuj", finish: "Zakończ historię", skip: "Pomiń", back: "Nowa historia",
  checkpoint: "Sprawdź zrozumienie", heard: "Wysłuchaj fragmentu, aby odblokować pytanie.", showQuestion: "Odpowiedz na pytanie", correct: "Zgadza się!", incorrect: "Niezupełnie. Oto co się stało:",
  translation: "Pokaż tłumaczenie", hideTranslation: "Ukryj tłumaczenie",
  complete: "Historia ukończona", score: "poprawnie za pierwszym razem", saving: "Zapisywanie postępów…", saveError: "Historia jest ukończona, ale nie udało się zapisać postępów. Spróbuj ponownie.",
  onAir: "NA ANTENIE", ready: "GOTOWE DO SŁUCHANIA", paused: "WSTRZYMANO", segment: "Część", of: "z", clear: "Wyczyść", answer: "Twoja odpowiedź", xp: "XP", review: "Przejrzyj odpowiedź i kontynuuj.",
  reviewStory: "Przejrzyj historię", sentencesCompleted: "ukończonych zdań",
  call: "Połączenie", practice: "Praktyka", story: "Opowieść", you: "Ty",
};

const ga = {
  preparingAudio: "Ag lódáil",
  modes: "Modhanna scéil", speaking: "Cleachtadh", radio: "Raidió", conversation: "Comhrá",
  radioIntro: "Éist le glaoch. Brúigh seinn, taifead do chuid línte do Tú, agus freagair ag gach sos.",
  conversationIntro: "Brúigh seinn chun an comhrá a leanúint. Taifead do chuid línte agus freagair an cheist.",
  yourTurn: "Do sheal le labhairt", speakingNow: "Ag labhairt", record: "Taifead", stopRecording: "Stad", connectingMic: "Ag nascadh",
  speechIncorrect: "Ní go díreach. Bain triail eile as.", recordingError: "Níorbh fhéidir an taifeadadh a chur i gcrích. Seiceáil do mhicreafón agus bain triail as arís.", micDenied: "Tabhair cead rochtana don mhicreafón agus bain triail eile as.",
  loading: "Do scéal á ullmhú…", loadingSub: "Ábhar an cheachta á ghiniúint…", generationError: "Níorbh fhéidir an scéal seo a ullmhú. Bain triail as arís.",
  audioError: "Níorbh fhéidir an fhuaim a sheinm. Tapáil seinn chun triail eile a bhaint as.", retry: "Bain triail eile as", play: "Seinn", pause: "Sos", resume: "Atosaigh", replay: "Athsheinn", listen: "Éist leis an sliocht",
  start: "Tosaigh an scéal", nextPair: "An chéad phéire eile", check: "Seol", next: "Lean ar aghaidh", finish: "Críochnaigh an scéal", skip: "Scipeáil", back: "Scéal nua",
  checkpoint: "Seiceáil do thuiscint", heard: "Éist leis an gcuid chun an cheist a dhíghlasáil.", showQuestion: "Freagair an cheist", correct: "Sin é go díreach!", incorrect: "Ní hea go díreach. Seo a tharla:",
  translation: "Taispeáin aistriúchán", hideTranslation: "Folaigh aistriúchán",
  complete: "Scéal críochnaithe", score: "ceart ar an gcéad iarracht", saving: "Dul chun cinn á shábháil…", saveError: "Tá do scéal críochnaithe, ach níorbh fhéidir an dul chun cinn a shábháil. Bain triail as arís.",
  onAir: "AR AN AER", ready: "RÉIDH LE hÉISTEACHT", paused: "AR SOS", segment: "Cuid", of: "de", clear: "Glan", answer: "Do fhreagra", xp: "XP", review: "Féach ar an bhfreagra agus lean ar aghaidh.",
  reviewStory: "Athbhreithnigh an scéal", sentencesCompleted: "abairtí críochnaithe",
  call: "Glao", practice: "Cleachtadh", story: "Scéal", you: "Tú",
};

const ar = {
  preparingAudio: "جارٍ التحميل",
  modes: "أوضاع القصة", speaking: "ممارسة", radio: "راديو", conversation: "محادثة",
  radioIntro: "استمع إلى مكالمة. اضغط على تشغيل، وسجل جملك لـ أنت، ثم أجب عند كل وقفة.",
  conversationIntro: "اضغط على تشغيل لمتابعة المحادثة. سجل جملك ثم أجب عن السؤال.",
  yourTurn: "دورك للتحدث", speakingNow: "يتحدث الآن", record: "تسجيل", stopRecording: "إيقاف", connectingMic: "اتصال",
  speechIncorrect: "ليس تمامًا. حاول مرة أخرى.", recordingError: "تعذر إكمال التسجيل. تحقق من الميكروفون وحاول ثانية.", micDenied: "يرجى السماح بالوصول إلى الميكروفون ثم إعادة المحاولة.",
  loading: "جارٍ إعداد قصتك…", loadingSub: "جارٍ إنشاء محتوى الدرس…", generationError: "تعذر إعداد هذه القصة. يرجى المحاولة مرة أخرى.",
  audioError: "تعذر تشغيل الصوت. اضغط تشغيل للمحاولة ثانية.", retry: "حاول مرة أخرى", play: "تشغيل", pause: "إيقاف مؤقت", resume: "استئناف", replay: "إعادة", listen: "استمع إلى المقطع",
  start: "ابدأ القصة", nextPair: "الزوج التالي", check: "تحقق", next: "متابعة", finish: "إنهاء القصة", skip: "تخطي", back: "قصة جديدة",
  checkpoint: "اختبر فهمك", heard: "استمع إلى المقطع لفتح السؤال.", showQuestion: "أجب عن السؤال", correct: "صحيح تمامًا!", incorrect: "ليس تمامًا. هذا ما حدث:",
  translation: "عرض الترجمة", hideTranslation: "إخفاء الترجمة",
  complete: "اكتملت القصة", score: "صحيحة من المحاولة الأولى", saving: "جارٍ حفظ التقدم…", saveError: "اكتملت القصة، ولكن تعذر حفظ التقدم. حاول مرة أخرى.",
  onAir: "على الهواء", ready: "جاهز للاستماع", paused: "متوقف مؤقتًا", segment: "الجزء", of: "من", clear: "مسح", answer: "إجابتك", xp: "XP", review: "راجع الإجابة ثم تابع.",
  reviewStory: "مراجعة القصة", sentencesCompleted: "جمل مكتملة",
  call: "مكالمة", practice: "ممارسة", story: "قصة", you: "أنت",
};

const hi = {
  preparingAudio: "लोड हो रहा है",
  modes: "कहानी मोड", speaking: "अभ्यास", radio: "रेडियो", conversation: "बातचीत",
  radioIntro: "एक कॉल सुनें। प्ले दबाएं, आप के संवाद रिकॉर्ड करें और हर विराम पर उत्तर दें।",
  conversationIntro: "बातचीत सुनने के लिए प्ले दबाएं। अपने संवाद रिकॉर्ड करें और प्रश्न का उत्तर दें।",
  yourTurn: "आपकी बोलने की बारी", speakingNow: "बोल रहे हैं", record: "रिकॉर्ड", stopRecording: "रोकें", connectingMic: "कनेक्ट",
  speechIncorrect: "काफी नहीं। पुनः प्रयास करें।", recordingError: "रिकॉर्डिंग पूरी नहीं हो सकी। अपना माइक्रोफ़ोन जांचें और पुनः प्रयास करें।", micDenied: "माइक्रोफ़ोन की अनुमति दें और पुनः रिकॉर्ड करें।",
  loading: "आपकी कहानी तैयार की जा रही है…", loadingSub: "पाठ तैयार हो रहा है…", generationError: "कहानी तैयार नहीं की जा सकी। कृपया पुनः प्रयास करें।",
  audioError: "ऑडियो नहीं चल सका। पुनः प्रयास करने के लिए प्ले दबाएं।", retry: "पुनः प्रयास करें", play: "चलाएं", pause: "रोकें", resume: "जारी रखें", replay: "पुनः चलाएं", listen: "अंश सुनें",
  start: "कहानी शुरू करें", nextPair: "अगला जोड़ा", check: "जांचें", next: "आगे बढ़ें", finish: "कहानी समाप्त करें", skip: "छोड़ें", back: "नई कहानी",
  checkpoint: "अपनी समझ जांचें", heard: "प्रश्न अनलॉक करने के लिए यह भाग सुनें।", showQuestion: "प्रश्न का उत्तर दें", correct: "बिल्कुल सही!", incorrect: "पूरी तरह सही नहीं। वास्तव में यह हुआ:",
  translation: "अनुवाद दिखाएं", hideTranslation: "अनुवाद छिपाएं",
  complete: "कहानी पूरी हुई", score: "पहली बार में सही", saving: "प्रगति सहेजी जा रही है…", saveError: "कहानी पूरी हो गई, लेकिन प्रगति सहेजी नहीं जा सकी। पुनः प्रयास करें।",
  onAir: "ऑन एयर", ready: "सुनने के लिए तैयार", paused: "रुक गया", segment: "भाग", of: "का", clear: "हटाएं", answer: "आपका उत्तर", xp: "XP", review: "उत्तर देखें, फिर आगे बढ़ें।",
  reviewStory: "कहानी की समीक्षा करें", sentencesCompleted: "वाक्य पूरे हुए",
  call: "कॉल", practice: "अभ्यास", story: "कहानी", you: "आप",
};

const zh = {
  preparingAudio: "加载中",
  modes: "故事模式", speaking: "练习", radio: "广播", conversation: "对话",
  radioIntro: "收听热线节目。点击播放，为你录制台词，并在每次停顿时回答问题。",
  conversationIntro: "点击播放聆听对话。录制你的台词，然后回答问题。",
  yourTurn: "轮到你说了", speakingNow: "正在说话", record: "录音", stopRecording: "停止", connectingMic: "连接中",
  speechIncorrect: "不太准确。再试一次吧。", recordingError: "录音未能完成。请检查麦克风后重试。", micDenied: "请允许麦克风权限，然后重试录音。",
  loading: "正在准备你的故事…", loadingSub: "正在生成课程内容…", generationError: "无法准备此故事，请重试。",
  audioError: "音频无法播放。轻点播放重试。", retry: "再试一次", play: "播放", pause: "暂停", resume: "继续", replay: "重播", listen: "收听选段",
  start: "开始故事", nextPair: "下一组", check: "提交", next: "继续", finish: "完成故事", skip: "跳过", back: "新故事",
  checkpoint: "理解检测", heard: "收听该片段以解锁问题。", showQuestion: "回答问题", correct: "完全正确！", incorrect: "不太对。实际情况如下：",
  translation: "显示翻译", hideTranslation: "隐藏翻译",
  complete: "故事完成", score: "首次尝试即答对", saving: "正在保存进度…", saveError: "故事已完成，但无法保存进度。请重试。",
  onAir: "正在直播", ready: "准备收听", paused: "已暂停", segment: "部分", of: "/", clear: "清除", answer: "你的答案", xp: "XP", review: "查看答案后继续。",
  reviewStory: "复习故事", sentencesCompleted: "个句子已完成",
  call: "通话", practice: "练习", story: "故事", you: "你",
};

const nah = {
  preparingAudio: "Tlacencahualli",
  modes: "Tlahtolpatolli", speaking: "Tlamachtiliztli", radio: "Tepoznotzalli", conversation: "Tlahtolnextiliztli",
  radioIntro: "Xiccaqui se notzaliztli. Xikpacho tlapohualli, xikihcuilo motlahtol ihuan xiknankili.",
  conversationIntro: "Xikpacho tlapohualli ma tlatzotzona. Xikihcuilo motlahtol ihuan xiknankili in tlahtlanilli.",
  yourTurn: "Motonal titlahtoz", speakingNow: "Tlahtoa", record: "Xikihcuilo", stopRecording: "Xikcahua", connectingMic: "Mocalaquia",
  speechIncorrect: "Ahmo yehyec. Okseppa xikchihua.", recordingError: "Ahmo ohuel omochihchiuh. Xikitta motepozihcuilol.", micDenied: "Xikcahuili motepozihcuilol ihuan okseppa xikyehyeko.",
  loading: "Mocencahua mozazanil…", loadingSub: "Mochihchihua motlamachtiliz…", generationError: "Ahmo ohuel omocencauh in zazanilli. Okseppa xikyehyeko.",
  audioError: "Ahmo ohuel otlatzotzon. Xikpacho okseppa.", retry: "Okseppa xikchihua", play: "Tlatzotzona", pause: "Mocahua", resume: "Xikpehualti", replay: "Okseppa", listen: "Xiccaqui",
  start: "Xikpehualti zazanilli", nextPair: "Okse omeyotl", check: "Xikyehyeko", next: "Xikpano", finish: "Xiktlami zazanilli", skip: "Xikpano", back: "Yancuic zazanilli",
  checkpoint: "Xikyehyeko motlamatiliz", heard: "Xiccaqui nin tlatectli inic tictlapoz in tlahtlanilli.", showQuestion: "Xiknankili tlahtlanilli", correct: "¡Cuali!", incorrect: "Ahmo yehyec. Nican tlen opanoc:",
  translation: "Xiknexti tlahtolcuezalli", hideTranslation: "Xiktlati tlahtolcuezalli",
  complete: "Otlantoc zazanilli", score: "cuali ika achto tlahtolcuezalli", saving: "Mopiya motlamachtiliz…", saveError: "Otlantoc mozazanil, pero ahmo omopix. Okseppa xikyehyeko.",
  onAir: "TLAPOHUALLI", ready: "CUALI TICCAQUIZ", paused: "MOCAHTOC", segment: "Xeloliztli", of: "itech", clear: "Xikpopolo", answer: "Monankililiz", xp: "XP", review: "Xikitta in nankililiztli ihuan xikpano.",
  reviewStory: "Xikitta zazanilli", sentencesCompleted: "tlahtolcuezaltin otlanqueh",
  call: "Notzaliztli", practice: "Tlamachtiliztli", story: "Zazanilli", you: "Tehwatl",
};

const yua = {
  preparingAudio: "U líik'sik",
  modes: "Bix u tsikbal", speaking: "Kanbal", radio: "T'aan tu k'áax", conversation: "Tsikbal",
  radioIntro: "U'uy jump'éel t'aan. P'iis páax, ts'íibt a t'aan ti' Teech, ka núuk tu láak' xot'ol.",
  conversationIntro: "P'iis páax utia'al a tsayik le tsikbalo'. Ts'íibt a t'aan ka núuk le k'áatchi'o'.",
  yourTurn: "A súutik a t'aan", speakingNow: "Táan u t'aan", record: "Ts'íibt", stopRecording: "P'áatik", connectingMic: "K'aaxik",
  speechIncorrect: "Ma' tu beeli'. Ka'a meentej.", recordingError: "Ma' béeychaj u ts'íibta'al. Ila a nu'ukul t'aan ka'a meentej.", micDenied: "Cha'aj u meyaj a nu'ukul t'aan ka ka'a meentej.",
  loading: "Táan u líik'sa'al a tsikbal…", loadingSub: "Táan u meenta'al a kanbal…", generationError: "Ma' béeychaj u líik'sa'al le tsikbala'. Ka'a yóot.",
  audioError: "Ma' béeychaj u páaxali'. P'iis ka'a téen.", retry: "Ka'a meentej", play: "Páax", pause: "Wáatal", resume: "K'a'am", replay: "Ka'a páax", listen: "U'uy le xot'olo'",
  start: "Káajsik tsikbal", nextPair: "U láak' ka'ap'éel", check: "Túuxtik", next: "Máansik", finish: "Ts'o'oksik tsikbal", skip: "Máansik", back: "Túumben tsikbal",
  checkpoint: "Ila a na'at", heard: "U'uy le xot'olo' utia'al a je'ik le k'áatchi'o'.", showQuestion: "Núuk k'áatchi'", correct: "¡Hach ma'alob!", incorrect: "Ma' tu beeli'. Le ba'ax úucho':",
  translation: "E'es suut t'aan", hideTranslation: "Ta'ak suut t'aan",
  complete: "Ts'o'ok tsikbal", score: "tu beel tu yáax p'iis", saving: "Táan u líik'sa'al…", saveError: "Ts'o'ok a tsikbal, ba'ale' ma' líik'i'. Ka'a meentej.",
  onAir: "TÁAN U PÁAXAL", ready: "LÍIK'IK UTIA'AL U'UYA'AL", paused: "WÁATAL", segment: "Xot'ol", of: "ti'", clear: "Tupik", answer: "A núukik", xp: "XP", review: "Ila a núukik ka máansik.",
  reviewStory: "Ka'a ilik tsikbal", sentencesCompleted: "t'aano'ob ts'o'okij",
  call: "T'aan", practice: "Kanbal", story: "Tsikbal", you: "Teech",
};

const dictionaries = {
  en, es, fr, de, it, pt, ja, ru, el, nl, pl, ga, ar, hi, zh, nah, yua,
};

export const storyCopy = (language) => {
  const normalized = String(language || "").toLowerCase().trim();
  const dict = dictionaries[normalized] || dictionaries.en;
  return { ...en, ...dict };
};
