// Episode engine UI copy in the ten app languages (QUEST_LOG_COPY pattern).
// Keep strings short and plain; {slots} are filled with fillCopy().

const COPY = {
  en: {
    talkTo: "Talk to {name}",
    goTo: "Go to {name}",
    pickUp: "Find {item}",
    pickedUp: "Picked up {item}",
    give: "Give",
    yourItems: "Your items",
    replayAudio: "Hear it again",
    choose: "Choose your answer",
    whichWrong: "Which one is wrong?",
    correct: "Correct!",
    tryAgain: "Not quite — try again",
    lastTry: "One more try",
    revealed: "The answer was: {answer}",
    assistMode: "Helper mode on — support text is visible",
    sayAloudOffer: "Say it aloud for ×2 points",
    sayAloudTarget: "Say: {text}",
    sayAloudRecall: "Say it from memory",
    sayAloudOpen: "Answer aloud in your own words",
    listening: "Listening…",
    speechPass: "Great — bonus earned!",
    speechMiss: "Close! No bonus this time",
    skip: "Skip",
    submit: "Submit",
    task: "Task {n} of {total}",
    finalTask: "Final task",
    score: "Score",
    start: "Start",
    recapTitle: "Review complete!",
    recapPracticed: "You practiced",
    recapMisses: "Worth another look",
    recapFlair: "Speaking bonus",
    recapBestSpoken: "Best spoken line",
    playAgain: "Play again",
    continue: "Continue",
    exit: "Exit",
    xpEarned: "+{xp} XP",
  },
  es: {
    talkTo: "Habla con {name}",
    goTo: "Ve a {name}",
    pickUp: "Busca {item}",
    pickedUp: "Recogiste {item}",
    give: "Entregar",
    yourItems: "Tus objetos",
    replayAudio: "Escuchar otra vez",
    choose: "Elige tu respuesta",
    whichWrong: "¿Cuál está mal?",
    correct: "¡Correcto!",
    tryAgain: "Casi — inténtalo otra vez",
    lastTry: "Un intento más",
    revealed: "La respuesta era: {answer}",
    assistMode: "Modo ayuda — se muestra el texto de apoyo",
    sayAloudOffer: "Dilo en voz alta por ×2 puntos",
    sayAloudTarget: "Di: {text}",
    sayAloudRecall: "Dilo de memoria",
    sayAloudOpen: "Responde en voz alta con tus palabras",
    listening: "Escuchando…",
    speechPass: "¡Muy bien! Bono ganado",
    speechMiss: "¡Casi! Sin bono esta vez",
    skip: "Saltar",
    submit: "Enviar",
    task: "Tarea {n} de {total}",
    finalTask: "Tarea final",
    score: "Puntos",
    start: "Empezar",
    recapTitle: "¡Repaso completado!",
    recapPracticed: "Practicaste",
    recapMisses: "Para repasar",
    recapFlair: "Bono de habla",
    recapBestSpoken: "Mejor frase hablada",
    playAgain: "Jugar otra vez",
    continue: "Continuar",
    exit: "Salir",
    xpEarned: "+{xp} XP",
  },
  pt: {
    talkTo: "Fale com {name}",
    goTo: "Vá para {name}",
    pickUp: "Procure {item}",
    pickedUp: "Você pegou {item}",
    give: "Entregar",
    yourItems: "Seus itens",
    replayAudio: "Ouvir de novo",
    choose: "Escolha sua resposta",
    whichWrong: "Qual está errada?",
    correct: "Correto!",
    tryAgain: "Quase — tente de novo",
    lastTry: "Mais uma tentativa",
    revealed: "A resposta era: {answer}",
    assistMode: "Modo ajuda — texto de apoio visível",
    sayAloudOffer: "Diga em voz alta por ×2 pontos",
    sayAloudTarget: "Diga: {text}",
    sayAloudRecall: "Diga de memória",
    sayAloudOpen: "Responda em voz alta com suas palavras",
    listening: "Ouvindo…",
    speechPass: "Muito bem! Bônus ganho",
    speechMiss: "Quase! Sem bônus desta vez",
    skip: "Pular",
    submit: "Enviar",
    task: "Tarefa {n} de {total}",
    finalTask: "Tarefa final",
    score: "Pontos",
    start: "Começar",
    recapTitle: "Revisão concluída!",
    recapPracticed: "Você praticou",
    recapMisses: "Para revisar",
    recapFlair: "Bônus de fala",
    recapBestSpoken: "Melhor frase falada",
    playAgain: "Jogar de novo",
    continue: "Continuar",
    exit: "Sair",
    xpEarned: "+{xp} XP",
  },
  it: {
    talkTo: "Parla con {name}",
    goTo: "Vai a {name}",
    pickUp: "Cerca {item}",
    pickedUp: "Hai preso {item}",
    give: "Consegna",
    yourItems: "I tuoi oggetti",
    replayAudio: "Ascolta di nuovo",
    choose: "Scegli la risposta",
    whichWrong: "Quale è sbagliata?",
    correct: "Corretto!",
    tryAgain: "Quasi — riprova",
    lastTry: "Un altro tentativo",
    revealed: "La risposta era: {answer}",
    assistMode: "Modalità aiuto — testo di supporto visibile",
    sayAloudOffer: "Dillo ad alta voce per ×2 punti",
    sayAloudTarget: "Di': {text}",
    sayAloudRecall: "Dillo a memoria",
    sayAloudOpen: "Rispondi ad alta voce con parole tue",
    listening: "In ascolto…",
    speechPass: "Ottimo! Bonus guadagnato",
    speechMiss: "Quasi! Niente bonus stavolta",
    skip: "Salta",
    submit: "Invia",
    task: "Compito {n} di {total}",
    finalTask: "Compito finale",
    score: "Punti",
    start: "Inizia",
    recapTitle: "Ripasso completato!",
    recapPracticed: "Hai praticato",
    recapMisses: "Da rivedere",
    recapFlair: "Bonus di pronuncia",
    recapBestSpoken: "Migliore frase parlata",
    playAgain: "Gioca ancora",
    continue: "Continua",
    exit: "Esci",
    xpEarned: "+{xp} XP",
  },
  fr: {
    talkTo: "Parle à {name}",
    goTo: "Va à {name}",
    pickUp: "Cherche {item}",
    pickedUp: "Tu as pris {item}",
    give: "Donner",
    yourItems: "Tes objets",
    replayAudio: "Écouter encore",
    choose: "Choisis ta réponse",
    whichWrong: "Laquelle est fausse ?",
    correct: "Correct !",
    tryAgain: "Presque — réessaie",
    lastTry: "Un dernier essai",
    revealed: "La réponse était : {answer}",
    assistMode: "Mode aide — texte de soutien visible",
    sayAloudOffer: "Dis-le à voix haute pour ×2 points",
    sayAloudTarget: "Dis : {text}",
    sayAloudRecall: "Dis-le de mémoire",
    sayAloudOpen: "Réponds à voix haute avec tes mots",
    listening: "Écoute…",
    speechPass: "Très bien ! Bonus gagné",
    speechMiss: "Presque ! Pas de bonus cette fois",
    skip: "Passer",
    submit: "Valider",
    task: "Tâche {n} sur {total}",
    finalTask: "Tâche finale",
    score: "Points",
    start: "Commencer",
    recapTitle: "Révision terminée !",
    recapPracticed: "Tu as pratiqué",
    recapMisses: "À revoir",
    recapFlair: "Bonus d'expression",
    recapBestSpoken: "Meilleure phrase dite",
    playAgain: "Rejouer",
    continue: "Continuer",
    exit: "Quitter",
    xpEarned: "+{xp} XP",
  },
  de: {
    talkTo: "Sprich mit {name}",
    goTo: "Geh zu {name}",
    pickUp: "Finde {item}",
    pickedUp: "{item} aufgehoben",
    give: "Geben",
    yourItems: "Deine Gegenstände",
    replayAudio: "Noch einmal anhören",
    choose: "Wähle deine Antwort",
    whichWrong: "Welche ist falsch?",
    correct: "Richtig!",
    tryAgain: "Fast — versuch es nochmal",
    lastTry: "Noch ein Versuch",
    revealed: "Die Antwort war: {answer}",
    assistMode: "Hilfemodus — Unterstützungstext sichtbar",
    sayAloudOffer: "Sag es laut für ×2 Punkte",
    sayAloudTarget: "Sag: {text}",
    sayAloudRecall: "Sag es auswendig",
    sayAloudOpen: "Antworte laut mit eigenen Worten",
    listening: "Ich höre…",
    speechPass: "Super! Bonus verdient",
    speechMiss: "Knapp! Diesmal kein Bonus",
    skip: "Überspringen",
    submit: "Absenden",
    task: "Aufgabe {n} von {total}",
    finalTask: "Letzte Aufgabe",
    score: "Punkte",
    start: "Start",
    recapTitle: "Wiederholung geschafft!",
    recapPracticed: "Du hast geübt",
    recapMisses: "Nochmal ansehen",
    recapFlair: "Sprech-Bonus",
    recapBestSpoken: "Bester gesprochener Satz",
    playAgain: "Nochmal spielen",
    continue: "Weiter",
    exit: "Beenden",
    xpEarned: "+{xp} XP",
  },
  ja: {
    talkTo: "{name}と話す",
    goTo: "{name}へ行く",
    pickUp: "{item}をさがす",
    pickedUp: "{item}を拾った",
    give: "わたす",
    yourItems: "もちもの",
    replayAudio: "もう一度聞く",
    choose: "答えをえらぶ",
    whichWrong: "どれがまちがい？",
    correct: "せいかい！",
    tryAgain: "おしい — もう一度",
    lastTry: "あと一回",
    revealed: "答えは: {answer}",
    assistMode: "ヘルプモード — サポート表示中",
    sayAloudOffer: "声に出すとポイント×2",
    sayAloudTarget: "言ってみて: {text}",
    sayAloudRecall: "思い出して言ってみて",
    sayAloudOpen: "自分の言葉で声に出して答えて",
    listening: "聞いています…",
    speechPass: "すばらしい！ボーナス獲得",
    speechMiss: "おしい！今回はボーナスなし",
    skip: "スキップ",
    submit: "送信",
    task: "タスク {n}/{total}",
    finalTask: "最後のタスク",
    score: "スコア",
    start: "スタート",
    recapTitle: "復習クリア！",
    recapPracticed: "練習した内容",
    recapMisses: "もう一度見直そう",
    recapFlair: "スピーキングボーナス",
    recapBestSpoken: "いちばんよかった発話",
    playAgain: "もう一度遊ぶ",
    continue: "つづける",
    exit: "終了",
    xpEarned: "+{xp} XP",
  },
  hi: {
    talkTo: "{name} से बात करें",
    goTo: "{name} पर जाएँ",
    pickUp: "{item} खोजें",
    pickedUp: "{item} उठाया",
    give: "देना",
    yourItems: "आपकी चीज़ें",
    replayAudio: "फिर से सुनें",
    choose: "अपना उत्तर चुनें",
    whichWrong: "कौन सा गलत है?",
    correct: "सही!",
    tryAgain: "लगभग — फिर कोशिश करें",
    lastTry: "एक और कोशिश",
    revealed: "उत्तर था: {answer}",
    assistMode: "सहायता मोड — मदद का टेक्स्ट दिख रहा है",
    sayAloudOffer: "ज़ोर से बोलें, ×2 अंक पाएँ",
    sayAloudTarget: "बोलें: {text}",
    sayAloudRecall: "याद से बोलें",
    sayAloudOpen: "अपने शब्दों में बोलकर उत्तर दें",
    listening: "सुन रहे हैं…",
    speechPass: "बहुत बढ़िया! बोनस मिला",
    speechMiss: "क़रीब! इस बार बोनस नहीं",
    skip: "छोड़ें",
    submit: "जमा करें",
    task: "कार्य {n}/{total}",
    finalTask: "अंतिम कार्य",
    score: "स्कोर",
    start: "शुरू करें",
    recapTitle: "समीक्षा पूरी!",
    recapPracticed: "आपने अभ्यास किया",
    recapMisses: "फिर से देखें",
    recapFlair: "बोलने का बोनस",
    recapBestSpoken: "सबसे अच्छा बोला वाक्य",
    playAgain: "फिर से खेलें",
    continue: "आगे बढ़ें",
    exit: "बाहर निकलें",
    xpEarned: "+{xp} XP",
  },
  ar: {
    talkTo: "تحدث مع {name}",
    goTo: "اذهب إلى {name}",
    pickUp: "ابحث عن {item}",
    pickedUp: "التقطت {item}",
    give: "سلِّم",
    yourItems: "أغراضك",
    replayAudio: "استمع مرة أخرى",
    choose: "اختر إجابتك",
    whichWrong: "أيها خاطئ؟",
    correct: "صحيح!",
    tryAgain: "قريب — حاول مرة أخرى",
    lastTry: "محاولة أخيرة",
    revealed: "كانت الإجابة: {answer}",
    assistMode: "وضع المساعدة — نص الدعم ظاهر",
    sayAloudOffer: "قلها بصوت عالٍ لتحصل على ×2",
    sayAloudTarget: "قل: {text}",
    sayAloudRecall: "قلها من الذاكرة",
    sayAloudOpen: "أجب بصوت عالٍ بكلماتك",
    listening: "نستمع…",
    speechPass: "رائع! حصلت على المكافأة",
    speechMiss: "قريب! لا مكافأة هذه المرة",
    skip: "تخطَّ",
    submit: "إرسال",
    task: "مهمة {n} من {total}",
    finalTask: "المهمة الأخيرة",
    score: "النقاط",
    start: "ابدأ",
    recapTitle: "اكتملت المراجعة!",
    recapPracticed: "لقد تدربت على",
    recapMisses: "يستحق مراجعة أخرى",
    recapFlair: "مكافأة التحدث",
    recapBestSpoken: "أفضل جملة منطوقة",
    playAgain: "العب مرة أخرى",
    continue: "متابعة",
    exit: "خروج",
    xpEarned: "+{xp} XP",
  },
  zh: {
    talkTo: "和{name}说话",
    goTo: "前往{name}",
    pickUp: "寻找{item}",
    pickedUp: "捡到了{item}",
    give: "交给",
    yourItems: "你的物品",
    replayAudio: "再听一遍",
    choose: "选择你的答案",
    whichWrong: "哪个是错的？",
    correct: "正确！",
    tryAgain: "差一点 — 再试一次",
    lastTry: "最后一次机会",
    revealed: "答案是：{answer}",
    assistMode: "帮助模式 — 显示辅助文字",
    sayAloudOffer: "大声说出来可得双倍分",
    sayAloudTarget: "请说：{text}",
    sayAloudRecall: "凭记忆说出来",
    sayAloudOpen: "用自己的话大声回答",
    listening: "正在听…",
    speechPass: "太棒了！获得奖励",
    speechMiss: "很接近！这次没有奖励",
    skip: "跳过",
    submit: "提交",
    task: "任务 {n}/{total}",
    finalTask: "最终任务",
    score: "得分",
    start: "开始",
    recapTitle: "复习完成！",
    recapPracticed: "你练习了",
    recapMisses: "值得再看看",
    recapFlair: "口语奖励",
    recapBestSpoken: "最佳口语句子",
    playAgain: "再玩一次",
    continue: "继续",
    exit: "退出",
    xpEarned: "+{xp} XP",
  },
};

export function getEpisodeUiCopy(lang = "en") {
  return COPY[lang] || COPY.en;
}

export function fillCopy(template, slots = {}) {
  return String(template || "").replace(/\{(\w+)\}/g, (match, key) =>
    slots[key] != null ? String(slots[key]) : match,
  );
}
