const GERMAN_COPY = {
  "Save failed": "Speichern fehlgeschlagen",
  "Error al guardar": "Speichern fehlgeschlagen",
  "Show translation": "Übersetzung anzeigen",
  "Subscription passcode is not configured":
    "Abonnement-Zugangscode ist nicht konfiguriert",
  "Passcode accepted": "Zugangscode akzeptiert",
  "Failed to save passcode": "Zugangscode konnte nicht gespeichert werden",
  "Connect your account to use this feature.":
    "Verbinde dein Konto, um diese Funktion zu nutzen.",
  "Account required": "Konto erforderlich",
  "Connect your account to analyze your level.":
    "Verbinde dein Konto, um dein Niveau zu analysieren.",
  "Analysis complete": "Analyse abgeschlossen",
  "Assigned level: {level}.": "Zugewiesenes Niveau: {level}.",
  "Analysis failed": "Analyse fehlgeschlagen",
  "Please try again later.": "Bitte versuche es später erneut.",
  "Couldn't find the current user.": "Der aktuelle Benutzer wurde nicht gefunden.",
  Help: "Hilfe",
  Cards: "Karten",
  Notes: "Notizen",
  Alphabet: "Alphabet",
  Path: "Pfad",
  Conversation: "Gespräch",
  Mode: "Modus",
  "Start proficiency test": "Einstufungstest starten",
  "Lesson Complete!": "Lektion abgeschlossen!",
  "XP Earned": "XP verdient",
  "Experience Points": "Erfahrungspunkte",
  Continue: "Weiter",
  "Keep learning": "Weiterlernen",
  Goal: "Ziel",
  "Daily goal reached!": "Tagesziel erreicht!",
  "You hit your XP goal for today.": "Du hast dein XP-Ziel für heute erreicht.",
  "Streak protected": "Serie geschützt",
  "Enter the passcode": "Zugangscode eingeben",
  Verifying: "Wird geprüft",
  Submit: "Absenden",
  "Invalid passcode. Please try again.":
    "Ungültiger Zugangscode. Bitte versuche es erneut.",
  "Browser is blocking the mic for this site. Click the lock icon → Site settings → Microphone → Allow, then reload.":
    "Der Browser blockiert das Mikrofon für diese Website. Klicke auf das Schloss → Website-Einstellungen → Mikrofon → Zulassen und lade neu.",
  "Microphone requires HTTPS (or localhost). Open the app over https:// and try again.":
    "Das Mikrofon benötigt HTTPS (oder localhost). Öffne die App über https:// und versuche es erneut.",
  "The microphone is busy (Zoom/Teams/Discord). Close other apps using the mic and try again.":
    "Das Mikrofon ist belegt (Zoom/Teams/Discord). Schließe andere Apps mit Mikrofonzugriff und versuche es erneut.",
  "No microphone was found or it’s disabled at the OS level.":
    "Es wurde kein Mikrofon gefunden oder es ist im Betriebssystem deaktiviert.",
  "Requested audio constraints are not supported by your mic.":
    "Die angeforderten Audioeinstellungen werden von deinem Mikrofon nicht unterstützt.",
  "Microphone error. If permissions look allowed, reload the page and try again.":
    "Mikrofonfehler. Wenn die Berechtigungen korrekt aussehen, lade die Seite neu und versuche es erneut.",
  "Your chats": "Deine Chats",
  "No saved chats": "Keine gespeicherten Chats",
  Delete: "Löschen",
  "Morpheme mode": "Morphem-Modus",
  "Break down words": "Wörter zerlegen",
  "New chat": "Neuer Chat",
  Menu: "Menü",
  Morphemes: "Morpheme",
  "Save chat": "Chat speichern",
  "What do you want to learn today?": "Was möchtest du heute lernen?",
  "Stop voice chat": "Sprachchat stoppen",
  "Start voice chat": "Sprachchat starten",
  Play: "Abspielen",
  "Ask about this lesson...": "Frag etwas zu dieser Lektion...",
  Send: "Senden",
  Stop: "Stopp",
  "Immersion Practice": "Immersionsübung",
  "3 tasks to use your language outside the app":
    "3 Aufgaben, um deine Sprache außerhalb der App zu nutzen",
  "Next batch in": "Nächster Stapel in",
  "Creating tasks...": "Aufgaben werden erstellt...",
  "Try again": "Erneut versuchen",
  "No tasks yet.": "Noch keine Aufgaben.",
  "Claim +50 XP": "+50 XP abholen",
  Claiming: "Wird abgeholt",
  Claimed: "Abgeholt",
  "Failed to award reward": "Belohnung konnte nicht vergeben werden",
  "Ready to refresh": "Bereit zum Aktualisieren",
  "Could not generate tasks. Please try again.":
    "Aufgaben konnten nicht erstellt werden. Bitte versuche es erneut.",
  "Enter a display name": "Anzeigenamen eingeben",
  "Display name updated": "Anzeigename aktualisiert",
  Error: "Fehler",
  "Get full access to more education apps and content":
    "Erhalte vollen Zugriff auf weitere Bildungs-Apps und Inhalte",
  "Create display name": "Anzeigenamen erstellen",
  "Saving…": "Wird gespeichert…",
  "Wallet not ready": "Wallet nicht bereit",
  "Please try again in a moment.": "Bitte versuche es gleich noch einmal.",
  "Invalid key": "Ungültiger Schlüssel",
  "Key must start with 'nsec'.": "Der Schlüssel muss mit „nsec“ beginnen.",
  "Couldn't create wallet": "Wallet konnte nicht erstellt werden",
  "Failed to create wallet": "Wallet konnte nicht erstellt werden",
  "Select an identity": "Identität auswählen",
  "Choose who receives your deposits before continuing.":
    "Wähle aus, wer deine Einzahlungen erhält, bevor du fortfährst.",
  "Couldn't create invoice": "Rechnung konnte nicht erstellt werden",
  "Failed to initiate deposit": "Einzahlung konnte nicht gestartet werden",
  "Address copied": "Adresse kopiert",
  "Lightning invoice copied to clipboard.":
    "Lightning-Rechnung in die Zwischenablage kopiert.",
  "Bitcoin wallet": "Bitcoin-Wallet",
  "Loading wallet…": "Wallet wird geladen…",
  "Choose a recipient": "Empfänger auswählen",
  "Select an option to enable deposits.":
    "Wähle eine Option, um Einzahlungen zu aktivieren.",
  "Create wallet": "Wallet erstellen",
  "Creating wallet…": "Wallet wird erstellt…",
  "Copy key": "Schlüssel kopieren",
  "Copy Secret Key": "Geheimen Schlüssel kopieren",
  "Secret key required": "Geheimer Schlüssel erforderlich",
  "Maybe later": "Vielleicht später",
  Done: "Fertig",
  Close: "Schließen",
  "View site": "Website ansehen",
  "Join us on Patreon": "Unterstütze uns auf Patreon",
  Join: "Beitreten",
  "Change display name": "Anzeigenamen ändern",
  "Display name": "Anzeigename",
  "Save": "Speichern",
  "Saving": "Speichern",
};

export const getGermanCopy = (text) => {
  if (typeof text !== "string") return "";
  return GERMAN_COPY[text] || "";
};
