const rows = {
  en: [
    "Your goal (optional)",
    "Talk with my grandmother about her childhood",
    "Save goal",
    "Pause",
    "Resume",
    "Mark achieved",
    "Clear",
    "Goal",
    "Try today's action",
    "Check my response",
    "Goal complete",
    "Saved",
  ],
  es: [
    "Tu meta (opcional)",
    "Hablar con mi abuela sobre su infancia",
    "Guardar meta",
    "Pausar",
    "Reanudar",
    "Marcar como lograda",
    "Borrar",
    "Meta",
    "Intenta la acción de hoy",
    "Revisar mi respuesta",
    "Meta completada",
    "Guardado",
  ],
  pt: [
    "Sua meta (opcional)",
    "Conversar com minha avó sobre a infância dela",
    "Salvar meta",
    "Pausar",
    "Retomar",
    "Marcar como alcançada",
    "Limpar",
    "Meta",
    "Tente a ação de hoje",
    "Verificar resposta",
    "Meta concluída",
    "Salvo",
  ],
  fr: [
    "Votre objectif (facultatif)",
    "Parler avec ma grand-mère de son enfance",
    "Enregistrer",
    "Mettre en pause",
    "Reprendre",
    "Marquer atteint",
    "Effacer",
    "Objectif",
    "Essayez l’action du jour",
    "Vérifier ma réponse",
    "Objectif accompli",
    "Enregistré",
  ],
  it: [
    "Il tuo obiettivo (facoltativo)",
    "Parlare con mia nonna della sua infanzia",
    "Salva obiettivo",
    "Pausa",
    "Riprendi",
    "Segna raggiunto",
    "Cancella",
    "Obiettivo",
    "Prova l’azione di oggi",
    "Verifica risposta",
    "Obiettivo completato",
    "Salvato",
  ],
  de: [
    "Dein Ziel (optional)",
    "Mit meiner Großmutter über ihre Kindheit sprechen",
    "Ziel speichern",
    "Pausieren",
    "Fortsetzen",
    "Als erreicht markieren",
    "Löschen",
    "Ziel",
    "Versuche die heutige Aufgabe",
    "Antwort prüfen",
    "Ziel abgeschlossen",
    "Gespeichert",
  ],
  ja: [
    "目標（任意）",
    "祖母と子供時代について話す",
    "目標を保存",
    "一時停止",
    "再開",
    "達成済みにする",
    "削除",
    "目標",
    "今日の課題に挑戦",
    "回答を確認",
    "目標完了",
    "保存しました",
  ],
  zh: [
    "你的目标（可选）",
    "和祖母聊聊她的童年",
    "保存目标",
    "暂停",
    "继续",
    "标记为已达成",
    "清除",
    "目标",
    "尝试今天的任务",
    "检查回答",
    "目标完成",
    "已保存",
  ],
  ru: [
    "Ваша цель (необязательно)",
    "Поговорить с бабушкой о её детстве",
    "Сохранить цель",
    "Пауза",
    "Продолжить",
    "Отметить достигнутой",
    "Очистить",
    "Цель",
    "Попробуйте задание дня",
    "Проверить ответ",
    "Цель выполнена",
    "Сохранено",
  ],
  ar: [
    "هدفك (اختياري)",
    "التحدث مع جدتي عن طفولتها",
    "حفظ الهدف",
    "إيقاف مؤقت",
    "استئناف",
    "تحديد كمُحقق",
    "مسح",
    "الهدف",
    "جرّب مهمة اليوم",
    "تحقق من إجابتي",
    "اكتمل الهدف",
    "تم الحفظ",
  ],
  hi: [
    "आपका लक्ष्य (वैकल्पिक)",
    "अपनी दादी से उनके बचपन के बारे में बात करना",
    "लक्ष्य सहेजें",
    "रोकें",
    "जारी रखें",
    "प्राप्त चिह्नित करें",
    "मिटाएँ",
    "लक्ष्य",
    "आज का कार्य आज़माएँ",
    "उत्तर जाँचें",
    "लक्ष्य पूरा",
    "सहेजा गया",
  ],
};
const keys = [
  "label",
  "example",
  "save",
  "pause",
  "resume",
  "achieve",
  "clear",
  "title",
  "attempt",
  "check",
  "complete",
  "saved",
];
export function goalCopy(lang = "en") {
  return Object.fromEntries(
    keys.map((key, i) => [key, (rows[lang] || rows.en)[i]]),
  );
}

const onboardingRows = {
  en: [
    "Language",
    "Goals",
    "What would you like to do in your new language?",
    "We'll create and tailor lessons to help you achieve your goals. You can change your goal later in {settingsIcon} settings, or leave it blank for now.",
  ],
  es: [
    "Idioma",
    "Metas",
    "¿Qué te gustaría hacer en el idioma que estás aprendiendo?",
    "Crearemos y adaptaremos lecciones para ayudarte a alcanzar tus metas. Puedes cambiar tu meta más tarde en {settingsIcon} ajustes o dejarla en blanco por ahora.",
  ],
  pt: [
    "Idioma",
    "Metas",
    "O que você gostaria de fazer no idioma que está aprendendo?",
    "Criaremos e adaptaremos aulas para ajudar você a alcançar suas metas. Você pode mudar sua meta depois nas {settingsIcon} configurações ou deixar em branco por enquanto.",
  ],
  fr: [
    "Langue",
    "Objectifs",
    "Que souhaitez-vous faire dans la langue que vous apprenez ?",
    "Nous créerons et adapterons des leçons pour vous aider à atteindre vos objectifs. Vous pourrez modifier votre objectif dans les {settingsIcon} paramètres ou laisser ce champ vide pour le moment.",
  ],
  it: [
    "Lingua",
    "Obiettivi",
    "Cosa vorresti fare nella lingua che stai imparando?",
    "Creeremo e adatteremo le lezioni per aiutarti a raggiungere i tuoi obiettivi. Puoi modificare il tuo obiettivo nelle {settingsIcon} impostazioni o lasciare il campo vuoto per ora.",
  ],
  de: [
    "Sprache",
    "Ziele",
    "Was möchtest du in deiner neuen Sprache tun?",
    "Wir erstellen und passen Lektionen an, damit du deine Ziele erreichst. Du kannst dein Ziel später in den {settingsIcon} Einstellungen ändern oder vorerst leer lassen.",
  ],
  ja: [
    "言語",
    "目標",
    "学んでいる言語で何をしたいですか？",
    "目標の達成をサポートするために、あなたに合ったレッスンを作成・調整します。目標は後で {settingsIcon} 設定から変更できます。今は空欄でも大丈夫です。",
  ],
  zh: [
    "语言",
    "目标",
    "你想用正在学习的语言做什么？",
    "我们会为你创建并调整课程，帮助你实现目标。你可以稍后在 {settingsIcon} 设置中修改目标，也可以暂时留空。",
  ],
  ru: [
    "Язык",
    "Цели",
    "Что вы хотите делать на изучаемом языке?",
    "Мы создадим и адаптируем уроки, чтобы помочь вам достичь ваших целей. Позже цель можно изменить в {settingsIcon} настройках или пока оставить поле пустым.",
  ],
  ar: [
    "اللغة",
    "الأهداف",
    "ماذا تريد أن تفعل باللغة التي تتعلمها؟",
    "سننشئ دروسًا ونخصصها لمساعدتك على تحقيق أهدافك. يمكنك تغيير هدفك لاحقًا في {settingsIcon} الإعدادات أو تركه فارغًا الآن.",
  ],
  hi: [
    "भाषा",
    "लक्ष्य",
    "आप नई भाषा में क्या करना चाहेंगे?",
    "हम आपके लक्ष्यों को हासिल करने में मदद के लिए पाठ बनाएँगे और उन्हें आपके अनुसार ढालेंगे। आप अपना लक्ष्य बाद में {settingsIcon} सेटिंग में बदल सकते हैं या अभी खाली छोड़ सकते हैं।",
  ],
};
export function goalOnboardingCopy(lang = "en") {
  const [language, goals, description, hint] =
    onboardingRows[lang] || onboardingRows.en;
  return { language, goals, description, hint };
}

const completionRows = {
  en: ["Completing task…", "Your lesson is finished. We couldn't save completion. Please retry.", "Retry"],
  es: ["Completando tarea…", "Terminaste la lección. No pudimos guardar la finalización. Inténtalo de nuevo.", "Reintentar"],
  pt: ["Concluindo tarefa…", "Você terminou a aula. Não foi possível salvar a conclusão. Tente novamente.", "Tentar novamente"],
  fr: ["Finalisation de la tâche…", "La leçon est terminée. Impossible d’enregistrer la fin. Veuillez réessayer.", "Réessayer"],
  it: ["Completamento dell’attività…", "Hai terminato la lezione. Non è stato possibile salvare il completamento. Riprova.", "Riprova"],
  de: ["Aufgabe wird abgeschlossen…", "Die Lektion ist beendet. Der Abschluss konnte nicht gespeichert werden. Bitte versuche es erneut.", "Erneut versuchen"],
  ja: ["課題を完了しています…", "レッスンは終了しました。完了を保存できませんでした。もう一度お試しください。", "再試行"],
  zh: ["正在完成任务…", "你已完成课程，但未能保存完成状态。请重试。", "重试"],
  ru: ["Завершение задания…", "Урок окончен. Не удалось сохранить завершение. Попробуйте ещё раз.", "Повторить"],
  ar: ["جارٍ إكمال المهمة…", "أنهيت الدرس. تعذّر حفظ الإكمال. يُرجى المحاولة مجددًا.", "إعادة المحاولة"],
  hi: ["कार्य पूरा किया जा रहा है…", "आपका पाठ पूरा हो गया है। पूरा होने की स्थिति सहेजी नहीं जा सकी। कृपया फिर कोशिश करें।", "फिर कोशिश करें"],
};
export function goalLessonCompletionCopy(lang = "en") {
  const [saving, error, retry] = completionRows[lang] || completionRows.en;
  return { saving, error, retry };
}
